### ISSUE TITLE
Consider changing new RouteValueDictionary(object) to a static factory method

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#127]
I just got bit by this again. We should try to make this less error prone for anyone using RVD as an infrastructure type.

This does what you want:
```
var source = new Dictionary<string, object>() { };
var destination = new RouteValueDictionary(source);
```

This does *not* do what you want, instead you get all the **properties** of Dictionary<>
```
IReadOnlyDictionary<string, object> source = new Dictionary<string, object>() { };
var destination = new RouteValueDictionary(source);
```

What happens is that `RouteValueDictionary(object)` is the best match, and then it does reflection to find all the properties.

The problem with just adding a `RouteValueDictionary(IReadOnlyDictionary<string, object>)` is that you'll get ambiguities trying to do trivial stuff. We need to think about this design more.

**Comment by Eilon** [comment]
@rynowak I have donated this bug to @kichalla.

@kichalla you have received a donation in the form of 1 bug.

**Comment by Eilon** [comment]
One possibly slightly gross solution is to do runtime type checks instead of having the compiler resolve (or fail to resolve) overloads. So, just take in `object` and check what you got at runtime and then extract the values from it in the most appropriate manner (read only dictionary, dictionary, property reflection, etc.).

**Comment by rynowak** [comment]
Yep. The *static factory method* suggestion is really independent from the problem that needs to be solved.

I seem to recall opening this super late at night :laughing:

**Comment by Eilon** [comment]
Yeah it was pretty late. Monday, Nov 7, 2014 @ 4:11PM :smile:

**Comment by kichalla** [comment]
commit: 1f6d3fe4cc8d66058fce84a40559ac7ea65d26ca
