### ISSUE TITLE
Routing produces unhelpful error message in case of malformed template with optional parameter

### ISSUE THREAD

**Issue by kulmugdha** [aspnet/Routing#148]
For template: [HttpGet("[controller]/[action]/{RouteValue?})")]
the error message is: 

Error: In a path segment that contains more than one section, such as a literal section or a parameter, there can only be one optional parameter. The optional parameter must be the last parameter in the segment and must be preceded by one single period (.).
Parameter name: routeTemplate

This message is trying to combine too many things together about optional parameter. We should separate these. Here are my suggestions:

1. 
[HttpGet("[controller]/[action]/{RouteValue?})")]
[HttpGet("[controller]/[action]/{RouteValue?}{param}")]
[HttpGet("[controller]/[action]/{RouteValue?}.")]

In the complex segment "{RouteValue?})" optional parameter "{RouteValue?}" should be the last parameter. No literal or parameter is not allowed after optional parameter.

2. [HttpGet("[controller]/[action]/{RouteValue?}{param?}")]
    [HttpGet("[controller]/[action]/{RouteValue?}.{param?}")]
    [HttpGet("[controller]/[action]/{param1}-{param2?}-{param3}-{param4?}")]

The complex segment "{RouteValue?}{param?}", contains more than one optional parameter. Only one optional parameter is allowed in a complex segment. The optional parameter must be the last parameter in the segment.

3. [HttpGet("[controller]/[action]/{RouteValue}-{param?}")]
    [HttpGet("[controller]/[action]/({param?}")]
    [HttpGet("[controller]/[action]/{RouteValue}{param?}")]

The complex segment "{RouteValue}-{param?}" has an optional parameter preceded by an invalid segment "-". Only valid literal to precede an optional parameter is a period (.).

In cases like `[HttpGet("[controller]/[action]/{RouteValue?}-{param}")]`, the optional parameter not being the last will be shown. If user fixes that, he'd run into another one for they not separated by a period.

**Comment by kulmugdha** [comment]
@yishaigalatzer -- Did you have a chance to look at different cases and related error messages. Do they look okay?

**Comment by danroth27** [comment]
f9a9b8068161ec6bb131a180cbb8406c693c1b03
