### ISSUE TITLE
Remove the use of Regex in the TemplateRouteParser

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Routing#164]
![image](https://cloud.githubusercontent.com/assets/95136/6698399/97f0a032-ccb5-11e4-99d0-333543308988.png)

**Comment by rynowak** [comment]
For context, the regex is showing up in profiles of app startup.

**Comment by Eilon** [comment]
Some pointers:
* https://github.com/aspnet/Routing/blob/328bdfd59779d8bcecd2d4d25af452def5054367/src/Microsoft.AspNet.Routing/Template/TemplateParser.cs#L195
* https://github.com/aspnet/Routing/blob/328bdfd59779d8bcecd2d4d25af452def5054367/src/Microsoft.AspNet.Routing/InlineRouteParameterParser.cs#L32

Please ensure that we have crazy amazing test coverage for both positive and negative cases before making code changes.

**Comment by kulmugdha** [comment]
@davidfowl Was there a particular route that you were using here? I tried MVC Sample, and I don't see these numbers.

**Comment by pranavkm** [comment]
### Before ###

![before](https://cloud.githubusercontent.com/assets/174281/9045834/59c61da8-39db-11e5-8471-9f78575c494f.PNG)

### After ###
![after](https://cloud.githubusercontent.com/assets/174281/9045835/5b2dad5a-39db-11e5-8f5a-9d625fca48c6.PNG)

**Comment by Eilon** [comment]
Wow, nice!
