### ISSUE TITLE
Consider changing _logger.LogInformation to _logger.LogVerbose in TemplateRoute.cs

### ISSUE THREAD

**Issue by dromanchenko** [aspnet/Routing#187]
Consider changing this code to _logger.LogVerbose

_logger.LogInformation(
                "Request successfully matched the route with name '{RouteName}' and template '{RouteTemplate}'.",
                Name,
                RouteTemplate);

That message is more like a low level debug. For example I have an application that uses the Info level to log things like "App Starting", "App Started", "Something configured or not". I can safely enable those logs without being aware of logs spamming. But if i do that, mvc starts spamming with the message above for each request. It would be cool if the routing uses the Verbose level, so that i could enable it in case i really want to debug each request.

**Comment by ajaybhargavb** [comment]
717260872222d2674a85e718ad72dca583b4ee82
