### ISSUE TITLE
Defect with POST and DELETE/PUT with the same path

### ISSUE THREAD

**Issue by taddeini** [aspnet/Routing#195]
(Reposted from https://github.com/aspnet/Home/issues/749)

We've noticed DELETE and PUT endpoints sometimes return 404s when they have the same routing configuration as a POST (e.g. POST /controller/operation and DELETE /controller/operation).

It turns out the 404s only happen if the DELETE/PUT is invoked before the POST when the application starts--after that all subsequent DELETE/PUT actions return 404s and POST actions are fine. If the application is then restarted and a POST is invoked first, then all actions are fine for the lifetime of the process.

I've verified this behavior for a POST and DELETE using MVC beta6 / IIS Express / Visual Studio 2015 RC.

**Comment by rynowak** [comment]
Can you upload or create a repo which demonstrates the problem in an isolated manner?

**Comment by rynowak** [comment]
Also, IIS can do wierd things with PUT and DELETE. Have you tried weblistener? This doesn't solve your issue but will help narrow it down

**Comment by danroth27** [comment]
Closing for now, but we are happy to reopen with more steps to reproduce the issue.
