### ISSUE TITLE
Route with dot in it

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Routing#198]
I'm trying to port over a rule like this from a prior version of ASP.NET MVC:
```
routes.MapRoute(
	name: "Page",
	template: "{action}.htm",
	defaults: new { controller = "Site" }
);
```

However IIS Express seems to always throw 404 errors. Any ideas on how to get this working? I tried commenting out `app.UseStaticFiles()` (thinking StaticFiles may be conflicting with it) but that didn't help.

Edit: This *does* work with Kestrel, so I assume it has something to do with how Visual Studio executes IIS Express.

**Comment by Eilon** [comment]
This might be an IIS "feature" where if it sees an extension it thinks it likes for static files, it eats it all up and no soup for you. I think if you set [`runAllManagedModulesForAllRequests`](http://www.iis.net/configreference/system.webserver/modules) to `true` in the `web.config` file (if you don't have one in the app, create a new one).

**Comment by Daniel15** [comment]
Yeah, I thought that might be the case. I don't use IIS a lot any more, my production sites are running on Mono + Nginx and I only use IIS Express for development, and `fastcgi-mono-server` doesn't have this issue (nor does Kestrel)

I don't think `web.config` works for ASP.NET 5 sites? I guess IIS might still read it since it doesn't really care that I'm using ASP.NET 5. In that case, does it need to go in `wwwroot` though, since I imagine that's the webroot IIS uses?

I just enabled RAMMFAR in the IIS Express config for my site (`.vs\config\applicationhost.config`) and that seemed to fix it. Not sure if I should be touching stuff in `.vs` though, I imagine Visual Studio might get angry at me at some point :zap:

**Comment by Eilon** [comment]
@Daniel15 yeah web.config definitely works for IIS settings - e.g. the `<system.webServer>` section. Setting ASP.NET settings in there won't do anything because they apply to ASP.NET 4.x and earlier.

I don't know about the stuff in the `.vs\...` folder - you can just add a `wwwroot/web.config` file and make sure you check that in. I don't think you're supposed to check in the `.vs` folder.

**Comment by Daniel15** [comment]
Yeah I don't have `.vs` checked in :) I'll try `wwwroot/web.config` tomorrow and see how that goes.

Closing this out since it's an IIS thing rather than an ASP.NET thing. Thanks for your help!

**Comment by Daniel15** [comment]
Maybe it's worth calling this out in the routing documentation, once it's written.

**Comment by Eilon** [comment]
@danroth27 for docs.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/371
