### ISSUE TITLE
Consider storing tokenized values in InlineConstraint

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Routing#199]
We do work to identify the constraint name and constraint arguments for `InlineConstraint`s as part of `InlineRouteParameterParser` but store the result as single constraint text string. Consequently, we end up doing work later to tokenize this later when creating route constraints from these strings - 

* https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNet.Routing/DefaultInlineConstraintResolver.cs#L46-L47.
* https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNet.Routing/DefaultInlineConstraintResolver.cs#L98

The suggestion is to parse these up front. This does mean `IInlineConstraintResolver` would have to change to take advantage of this:

```
public interface IInlineConstraintResolver
    {
        IRouteConstraint ResolveConstraint(
              string constraintName, IEnumerable<string> constraintValues);
    }
```

Thoughts?

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by rynowak** [comment]
@Eilon @danroth27 - we made this change along time ago, but not for perf reasons

https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNet.Routing/Template/TemplatePart.cs#L53

Closing this out as it's not really valid from a perf POV as it's just idle speculation.
