### ISSUE TITLE
Switch InnerAttributeRoute to log at Debug level, or make it configurable

### ISSUE THREAD

**Issue by timothy-shields** [aspnet/Routing#202]
I'm using `1.0.0-beta6`. `Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute` logs an awful lot at the info level.  For example, when logging to console I get this kind of message every time a request hits my service:

    info    : [Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute] Request successfully matched the route with name '{RouteName}' and template '{RouteTemplate}'

Is there a way I can disable this?  Or modify the level at which the `InnerAttributeRoute` logs?

**Comment by timothy-shields** [comment]
I just realized this should be an `aspnet / Mvc` issue instead, since that's where the `InnerAttributeRoute` class resides, but I don't know how to migrate it.

**Comment by rynowak** [comment]
Moved to aspnet/Mvc#2996
