### ISSUE TITLE
Is there any plan to add domain supports into route template?

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Routing#203]
Such as "//{id}.blablabla.com/{controller}/{action}"

**Comment by danroth27** [comment]
Routing currently is setup only to deal with the path and it would be a pretty significant change to start dealing with the host. It's certainly possible to do, but we would want to understand the scenarios better before we embarked on the work.

**Comment by Kagamine** [comment]
I think many projects need this. Such as multi-users blog systems, It will provide user a second-level domain, or a document website like readthedocs.

**Comment by Kagamine** [comment]
I hope I can use both path rules and host rules at the same time.

x.MapRoute("//{id}.*.*/{controller}/{action}");
x.MapRoute("/{controller}/{action}/{id?}");

**Comment by davidfowl** [comment]
We're not going to be doing this for 1.0. Moving it I to the backlog and we'll look at this later

**Comment by Kagamine** [comment]
:(

**Comment by ishvedov** [comment]
Another use case: domain of the language.
For example: en.domain.com, de.domain.com
Embodiment: http://blog.maartenballiauw.be/post/2015/02/17/Domain-Routing-and-resolving-current-tenant-with-ASPNET-MVC-6-ASPNET-5.aspx

**Comment by Kagamine** [comment]
+1 for domain routing

**Comment by anorborg** [comment]
I would also suggest this feature would make it easier to migrate from classic ASP.NET (i.e 4.5) to ASP.NET Core. If I had a domain routing in front, I could easily implement all my new features in ASP.NET Core and forward all classic requests to my legacy app. This would make it much easier to slowly migrate to the new Core platform while not affecting the legacy application

**Comment by ThreeSevenths** [comment]
It should be pretty easy to create an IDomainAccessor service and drop it into your service collection. I don't think it belongs in routing since routing's job is to find the correct action. Domains are almost always data in these cases and should be provided perhaps in model binding or as a service accessor.
