### ISSUE TITLE
Routing hijacking requests to *.asp

### ISSUE THREAD

**Issue by davezych** [aspnet/Routing#207]
This might be slightly related to #47. I'm using beta7. 

I have a site I'm building that includes (for various reasons) a few classic asp pages. The routing module seems to be hijacking requests to *.asp pages and doesn't allow the classic ASP handler to process them. It either

- Returns nothing or
- Returns the unprocessed page in plain text if I use `UseDefaultFiles`

Interestingly enough if I hit a *.asp page as the first request to the site on a cold startup, it process the page correctly, and every subsequent page load to a classic asp page seems to work correctly even after hitting a MVC page. But if I hit a MVC page first, the routing seems to hijack the request and returned what I mentioned above.

I'm not sure if this is a bug in the current implementation, and/or whether or not `IgnoreRoute` will resolve this once it's implemented.

**Comment by Eilon** [comment]
I doubt this is a routing issue. I'm guessing it's an ASP.NET activation issue.

I don't think you can mix Classic ASP and ASP.NET in the same site - at least certainly not in ASP.NET 5.

@Tratcher @moozzyk could this be related to that thing where if the first request in IIS might skip Helios if it gets eaten by another IIS module?

**Comment by Tratcher** [comment]
Yes, it sounds very similar to the static files scenario we had trouble with.

UseDefaultFiles and UseStaticFiles should not have any affect, they don't process *.asp pages.

**Comment by danroth27** [comment]
We should try this with the new HttpPlatformHandler + Kestrel setup.

**Comment by ajaybhargavb** [comment]
Spoke to @Tratcher. Tried running an asp site and an MVC site simultaneously. It works if the asp site is root and the MVC site is in a virtual directory but not the other way round. 
The issue of route being hijacked doesn't happen anymore as we no longer use Helios.

**Comment by ajaybhargavb** [comment]
Actually it works even if the classic asp is a sub app and MVC is root. It just needs a web.config that specifies `<remove name="httpPlatformHandler" />`.

Summary:
There are two ways to run an MVC and a classic asp site simultaneously
* Have the classic asp as root and add the MVC app as a sub-app using virtual directory.
In this case the Startup.cs needs to be modified to map the sub-app path to the configure method.
```C#
public void Configure(
    IApplicationBuilder app,
    IHostingEnvironment env,
    ILoggerFactory loggerFactory)
{
    app.Map("/mvcsite", subApp =>
    {
        ConfigureSub(subApp, env, loggerFactory);
    });
}
```

* Have MVC as root and add the classic asp as a sub app using virtual directory.
No need to change Startup.cs. Just add the following web.config in the classic asp site.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="httpPlatformHandler" />
    </handlers>
  </system.webServer>
</configuration>
```
