### ISSUE TITLE
Consider adding extension method to the RouteCollection to register a delegate callback for a route

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Routing#21]
It would make writing inline handlers easier.

```C#
routes.MapRoute("hello/{name}", async ctx =>
{
    await ctx.HttpContext.Response.WriteAsync("Hello " + ctx.Values["name"]);
});
```

Somebody could even extend this and write a routing microframework:

```C#
routes.Get("hello/{name}", async ctx => 
{
    await ctx.HttpContext.Response.WriteAsync("Hello " + ctx.Values["name"]);
});
```

**Comment by Eilon** [comment]
@davidfowl would this make routing better outside of MVC?

**Comment by laskoviymishka** [comment]
@davidfowl does this issue still active? right now proposed feature already presented in rc2

**Comment by Eilon** [comment]
Ah, yes, we actually did end up doing this in 1.0.0-rc2. See the APIs here: https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/RequestDelegateRouteBuilderExtensions.cs

**Comment by atrauzzi** [comment]
Nice!!
