### ISSUE TITLE
Template matching culture comparison

### ISSUE THREAD

**Issue by bbowyersmyth** [aspnet/Routing#210]
Is the template matching intended to be a CurrentCulture based comparison? https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNet.Routing/Template/TemplateMatcher.cs#L207 
Might be more readable to be explicit about the StringComparison there.

**Comment by pranavkm** [comment]
It probably needs to be Culture insensitive and I guess case insensitive (@rynowak?) . Could you send a PR for this?

**Comment by rynowak** [comment]
Yes, everything that I can think of in routing should be `OrdinalIgnoreCase`.

**Comment by Eilon** [comment]
Agreed, this definitely looks like a bug.

**Comment by ajaybhargavb** [comment]
d5d11eb30e008c2fc22af30dd57aeebdee4deeb1

**Comment by DaveVdE** [comment]
If URLs are case-sensitive, why is literal matching done with `OrdinalIgnoreCase`?

**Comment by Eilon** [comment]
URLs are technically case-sensitive as far as the person *constructing* the URL is concerned, but it's up to a web server to interpret a URL however it wants. So, in the case of ASP.NET, the routing system is entirely case-insensitive.
