### ISSUE TITLE
String route binding still has URI escape sequences

### ISSUE THREAD

**Issue by flipchart** [aspnet/Routing#221]
With a controller as below:

    [Route("api")]
    public class ValuesController : Controller
    {
        [HttpGet("{param}")]
        public string Get(string param)
        {
            return param;
        }
    }

requests to this action which contain URI escape sequences (e.g. `%20` for space) are carried through in the `param` value, rather than being escaped as they were in ASP.net 4; i.e. `GET /api/a%20b` assigns `param` the value `"a%20b"` instead of `"a b"`

**Comment by rynowak** [comment]
This is very likely a manifestation of this kestrel bug: https://github.com/aspnet/KestrelHttpServer/issues/124
