### ISSUE TITLE
Optional parameters not working with attribute routing

### ISSUE THREAD

**Issue by lukepfeiffer10** [aspnet/Routing#222]
I'm not sure if this is the place to report this issue but since this issue deals with WebApi routing I figured I would post here.

I am currently experiencing this issue and this stackoverflow post summarizes it quite nicely. 

[SO Post](http://stackoverflow.com/questions/33365379/attribute-routing-optional-parameter-not-working)

**EDIT:**

Not sure if this can even be classified as an issue maybe it is just the blog post referenced in the stackoverflow post having an incorrect or out of date way of doing optional parameters.

**Comment by danroth27** [comment]
Right, to specify optional parameters in a Web API action in ASP.NET Web API you had to specify a default value for the parameter in the action method signature. 

In MVC 6 the behavior is a bit different. There is no longer any method overloading semantics. Nullable types are optional by default.

**Comment by rynowak** [comment]
> Nullable types are optional by default.

All parameters are optional in MVC.
