### ISSUE TITLE
Can`t get route segment in custom middleware

### ISSUE THREAD

**Issue by Codenator81** [aspnet/Routing#223]
After initialized mvc in startup.cs it is not possible get route segment in custom middleware.
Related issue aspnet/Localization#122

**Comment by Eilon** [comment]
@Codenator81 routing happens *after* middleware runs, so I think this ordering is incorrect. We are looking to enable middleware to run as a result of routing in https://github.com/aspnet/Routing/issues/224, and I think that would enable you to do this.

**Comment by Codenator81** [comment]
@Eilon Great news! This will be very helpful for many scenarios
