### ISSUE TITLE
Update sample app to show more common routing patterns and add functional tests for it

### ISSUE THREAD

**Issue by Eilon** [aspnet/Routing#228]
The current sample shows some obscure usage of routing. It should instead show typical patterns and extensibility. And then add functional tests to it.

**Comment by Eilon** [comment]
Can go over it with me or @rynowak if anything isn't clear.

**Comment by rynowak** [comment]
Things to include:

- MapRoute with a middleware 
- Map[Verb] with a delegate
- Route handler that prints route values
