### ISSUE TITLE
Clearly document options and all the semantics of defaults

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Routing#235]
When I'm using `MapRoute`, it would be nice if I could know the full list of possible options that can go into the defaults object and what each option does.

**Comment by Eilon** [comment]
@atrauzzi sorry exactly what options are you looking for? It's just a dictionary - no tokens have any special meaning in there.

**Comment by atrauzzi** [comment]
Don't `controller` and `action` have any special meaning to the framework there in determining what gets run?

**Comment by Eilon** [comment]
They have a special meaning in MVC, but not in routing. You can route to non-MVC stuff as well (especially with some of the newest routing features, which allows routing to any middleware).

**Comment by atrauzzi** [comment]
@Eilon - That's actually super helpful to know.  So I guess that means this should be a request on the MVC repository instead?

**Comment by Eilon** [comment]
More than anything, it's probably a topic for the https://github.com/aspnet/Docs/ repo. I'm not sure where this would be documented in MVC itself.
