### ISSUE TITLE
Do a full optimization pass on Link Generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#236]
We haven't put any work yet into optimizing the link generation process, but we need to give it a look - primarily for allocations of 'scratch' data structures like dictionaries.

**Comment by Eilon** [comment]
@ajaybhargavb @rynowak can we expect anything here for 1.0.0? I don't think we have time to do anything significant here.

**Comment by rynowak** [comment]
![image](https://cloud.githubusercontent.com/assets/1430011/15826968/83fa2dd2-2bbe-11e6-8bc6-93ce218c7b2a.png)

This picture depicts Queen Ati, wife of King Perahu of Punt, depicted on Pharaoh Hatshepsut's temple at Deir el-Bahri. (Thanks [wikipedia](https://en.wikipedia.org/wiki/Land_of_Punt))

I suggest we send this issue on a voyage to the Land of Punt

**Comment by Eilon** [comment]
Punt to never, or punt to not-now-but-later?

**Comment by rynowak** [comment]
Punt to 1.0.1 :+1:

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2674
