### ISSUE TITLE
Revive ifdef-ed TemplateRouteTest

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Routing#242]
There's a bunch of tests in `TemplateRouteTest` https://github.com/aspnet/Routing/blob/dev/test/Microsoft.AspNet.Routing.Tests/Template/TemplateRouteTest.cs#L633 that are ifdef out.

**Comment by Eilon** [comment]
A bunch of `#ifdef`ed stuff in https://github.com/aspnet/Routing/blob/d4b96b27c0a7ab051b6b90a72a131e5042e141be/test/Microsoft.AspNet.Routing.Tests/Template/TemplateBinderTests.cs as well.

**Comment by Eilon** [comment]
@javiercn please sync with @pranavkm / @rynowak to assess what the expectations are here.

**Comment by javiercn** [comment]
I've searched though the routing repository with 
```
Get-ChildItem -Filter *.cs -Recurse | select-string '#if' -SimpleMatch
```
And the results are 
```
src\Microsoft.AspNetCore.Routing\Internal\TaskCache.cs:10:#if DOTNET5_4
test\Microsoft.AspNetCore.Routing.Tests\Template\TemplateBinderTests.cs:694:#if ROUTE_COLLECTION
test\Microsoft.AspNetCore.Routing.Tests\Template\TemplateBinderTests.cs:946:#if DATA_TOKENS
test\Microsoft.AspNetCore.Routing.Tests\Template\TemplateBinderTests.cs:972:#if ROUTE_FORMAT_HELPER
test\Microsoft.AspNetCore.Routing.Tests\Template\TemplateBinderTests.cs:1027:#if CONSTRAINTS
```

https://github.com/aspnet/Routing/blob/dev/test/Microsoft.AspNetCore.Routing.Tests/Template/TemplateBinderTests.cs

**Comment by pranavkm** [comment]
`TaskCache` is just code (and that looks ok). Presumably `TemplateRouteTest` got renamed to `TemplateBInderTests` at some point.

**Comment by Eilon** [comment]
Moving to 1.0.0.

**Comment by rynowak** [comment]
Not happening for 2.0.0

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2673
