### ISSUE TITLE
Implement chaining for link generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#250]
We need a pattern to 'chain' link generation when a Route is forwarding to another Route. 

This currently doesn't work today:
```
Route("{locale}") -> Route("{controller}/{action}/{id?}")
```

If you tried to generate a link with `new { controller = "Home", action = "Index", locale = "en-CA" }` then you'd get `/Home/Index` not `/en-CA/Home/Index`

**Comment by Eilon** [comment]
@ajaybhargavb please sync with @rynowak on how to approach this.

**Comment by ajaybhargavb** [comment]
I built a sample to demonstrate how we can currently implement this scenario.

`api/v2/Home/Index`
Consider a route that understands the api version part of the URL which then forwards to another route that understands the rest.

In Startup:
```C#
    routes.Routes.Add(new ApiVersionRoute(new Route(routes.DefaultHandler, "{controller}/{action}/{id?}", inlineConstraintResolver)));
```


GetVirtualPath in ApiVersionRoute:
```C#
public VirtualPathData GetVirtualPath(VirtualPathContext context)
{
    var version = "v2";
    if (context.Values.ContainsKey("apiVersion"))
    {
        version = context.Values["apiVersion"].ToString();
    }

    var data = _next.GetVirtualPath(context);
    if (data != null)
    {
        return new VirtualPathData(_next, "api/" + version + data.VirtualPath, data.DataTokens);
    }

    return null;
}
```
Now if we generate a link with `new { controller = "Home", action = "Index", apiVersion = "v3" }`, we'll get `api/v3/Home/Index`

Not sure if this is a good enough scenario to have the sample checked in somewhere.

**Comment by Eilon** [comment]
@ajaybhargavb ping reminder to close this.

**Comment by ajaybhargavb** [comment]
Closing this as there is no further action required.
