### ISSUE TITLE
App relative url and routing

### ISSUE THREAD

**Issue by leonardlabat** [aspnet/Routing#251]
Hello,

I'm hosting an asp.net 5 app in a "sub application" - I mean not at my IIS web site root level. So that my app is accessible through this kind of path : http://localhost/myapp. In this specific case, routing doesn't seem to work. But, if I'm querying directly Kestrel (I mean the http://localhost:someport url), routing is fine.

That seems to be caused by the **TemplateRoute** class implementation. The code from the route matching algorithm uses current request's full path, but not the relative one.

Here's the line that i'm talking about :
     var requestPath = context.HttpContext.Request.Path;

In the previous **UrlRoutingModule** implementation, the relative path was used :
     string appRelativeCurrentExecutionFilePath = httpContext.Request.AppRelativeCurrentExecutionFilePath;

I guess that this relative stuff might be related to my iis hosting scenario and is not supported in the http abstractions provided by aspnet 5. But, how should I handle this scenario ? Should I extract my current site app name from configuration and dynamically try to add it to routes ? This seems to me an awful solution :/

Thanks a lot :)

**Comment by Tratcher** [comment]
This is a known issue in RC1 https://github.com/aspnet/IISIntegration/issues/14 that should be fixed in RC2. In the meantime it can be worked around by fixing up the path using something like Map.

**Comment by rynowak** [comment]
@leonardlabat see the workaround here: https://github.com/aspnet/Hosting/issues/416#issuecomment-149046552

**Comment by leonardlabat** [comment]
Thanks for the answer
