### ISSUE TITLE
Add global MaxUrlSegments constraint

### ISSUE THREAD

**Issue by benaadams** [aspnet/Routing#254]
Failure state: current `414 URI Too Long` old `414 Request-URI Too Large`

*"The URI provided was too long for the server to process. Often the result of too much data being encoded as a query-string of a GET request, in which case it should be converted to a POST request."* [RFC 7231](https://tools.ietf.org/html/rfc7231)

**IIS** [default](https://www.iis.net/configreference/system.applicationhost/sites/sitedefaults/limits) `maxUrlSegments` 32
**http.sys** [default](https://support.microsoft.com/en-us/kb/820129) `UrlSegmentMaxCount` 255

Will currently be enforced by reverse proxy config (e.g. IIS/nginx) when deployed in recommended configuration - but not in pure Kestrel deployment.

**Comment by rynowak** [comment]
@benaadams - why is this a routing concern?

**Comment by benaadams** [comment]
Thought it was where the path was parsed (beyond general length in the server). No too fussed though only seems to be an IIS/http.sys thing.

However... do you think there should be a `MaxPathLength` https://github.com/aspnet/KestrelHttpServer/issues/476  beyond just a general "total header bytes"  `431 Request Header Fields Too Large`

**Comment by rynowak** [comment]
> Thought it was where the path was parsed (beyond general length in the server). No too fussed though only seems to be an IIS/http.sys thing

We 'iterate' the path segments, but only based on the number of route segments you specified in your route. So if we're parsing 50 segments, it's because you defined a route for 50 segments.

> However... do you think there should be a MaxPathLength aspnet/KestrelHttpServer#476 beyond just a general "total header bytes" 431 Request Header Fields Too Large

I'd expect so, but this isn't the place to discuss or enforce that.

**Comment by benaadams** [comment]
Ok, seems fine then - closing this.
