### ISSUE TITLE
Hard to make an exclusion constraint for the routing

### ISSUE THREAD

**Issue by ilya-git** [aspnet/Routing#260]
There is a common scenario when you would like to exclude some paths from the route. E.g. in a SPA app you generally want to map all the /api routes to controllers, and all other non static files to Home\Index so that client will handle the urls in the browser (e.g. angular). It can be done like that: "template: {*url}". Now the drawback is that e.g. lib/someCode.js will also fall for this route if the static file does not exist. So in case you have a problem you won't see a 404, but rather it will return your main view which is a bit weird. To avoid that situation we can exclude the routes that contain "." e.g. It is possible to do with regex, but that's not so efficient and regex is rather nontrivial to achieve it. So it will be good to have the exclusion constraint (maybe inclusion as well) that can apply simply.

**Comment by rynowak** [comment]
@SteveSandersonMS has already built something like that here for exactly this purpose. 

https://github.com/aspnet/NodeServices/blob/master/samples/angular/MusicStore/Startup.cs#L123
https://github.com/aspnet/NodeServices/blob/master/Microsoft.AspNet.SpaServices/SpaRouteConstraint.cs

**Comment by ilya-git** [comment]
Yes, I have built it like that as well myself, and wanted to make a pull request, but there were some legal issues with that, so it's not a problem for me to make, but I thought it would be beneficial to have that constraint in the framework itself.

**Comment by Eilon** [comment]
Moving to backlog.

I think in the meantime if your have the Static Files middleware before MVC (which should always be the case), then for the most part having a catch-all route (e.g. a route with a template like `{*everything}`) that maps all unmatched requests to controller=Home, action=Index should work.

**Comment by ilya-git** [comment]
The problem is not that there are no catch-all route, but in the fact that the catch-all route will return the default action for all the "would be" errors (like when you don't have a .js or .html file for example).
