### ISSUE TITLE
Not found file falls through to MVC route

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Routing#262]
_From @damienpontifex on December 17, 2015 7:54_

I am using ASP.NET to serve content for an AngularJS based site. As such, I have the static file middleware with MVC. The MVC routes should basically serve the angular site unless a specific action was found. See code below:

```c#
app.UseStaticFiles();

app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");

    // 404 routingfor SPA
    routes.MapRoute("spa-fallback", "{*anything}", new { controller = "Home", action = "Index" });
});
```

My problem occurs when the request for an angular html component (e.g. ./components/app/app.html) cannot be found and I would expect a 404 to be returned. The problem is the default content from Index.cshtml is actually returned in this case. i.e. it is falling through to the default `HomeController.Index` route and returning the entire view.

Is this specific to angular as it seems to be request the html file via ajax? Or a problem with my setup? Or a bug when the file isn't found?

_Copied from original issue: aspnet/StaticFiles#97_

**Comment by Tratcher** [comment]
By design. All middleware either handle a request or let it pass through to the next middleware. If static files can't match the url to a file then it falls through. A 404 isn't sent unless you reach the end of the pipeline.

In your example you shouldn't have MVC set up to consume all requests because it really will consume all requests. Or at the very least you should set it to a special 404 page rather than your home page.

**Comment by Tratcher** [comment]
_From @damienpontifex on December 18, 2015 1:13_

Thanks @Tratcher 

I assume this {*anything} route is the only way to get all new requests routed through to the index page so angular can handle the routing/components? The angular routing also handles the 404/otherwise case.

Is there a way to have it ignore anything with a path extension? i.e. *.html, *.css etc

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Routing/issues/260

**Comment by ilya-git** [comment]
The easiest way that I found for that is the one described in the referenced item: just define your own constraint, e.g. : DoesNotContainConstraint : IRouteConstraint (You can check for an example in this repository), you whole code will be like that:

public DoesNotContainConstraint(string substring)
{
      m_Substring = substring;
}

public bool Match(HttpContext httpContext, IRouter route, string routeKey, IDictionary<string, object> values, RouteDirection routeDirection)
        {
           .... // Default stuff

            if (values.TryGetValue(routeKey, out routeValue)
                && routeValue != null)
            {
                string parameterValueString = Convert.ToString(routeValue, CultureInfo.InvariantCulture);

                return !parameterValueString.Contains(m_Substring);
            }

            return true;
        }
