### ISSUE TITLE
RequestDelegateRouteBuilderExtensions are in the wrong namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Routing#267]
They should be in Microsoft.AspNet.Routing /cc @rynowak

**Comment by davidfowl** [comment]
Also why not just put them in the routing assembly? We have a whole .Extensions assembly for a single class.

**Comment by rynowak** [comment]
Nah, these are only used from startup code.

**Comment by rynowak** [comment]
> Also why not just put them in the routing assembly? We have a whole .Extensions assembly for a single class.

Our previous conclusion from discussing this was that it should be a separate package. I'm fine with moving them back

**Comment by davidfowl** [comment]
> Nah, these are only used from startup code.

They should still be in the right namespace. They're extending the `IRouteBuilder` not the `IApplicationBuilder`. 

We should totally put them back in the main assembly, they are just sugar methods.

**Comment by rynowak** [comment]
So then we should move `IRouteBuilder`? What you're suggesting isn't an improvement.

Yeah let's move these back into the routing package.

**Comment by rynowak** [comment]
d97947e229d9e9c8c5057ca5c67eb9a38c4ce53b
