### ISSUE TITLE
Support default action in attribute routing?

### ISSUE THREAD

**Issue by srayuws** [aspnet/Routing#268]
In the old version ASP.NET MVC 5, I can write a controller with a default action using attribute routing like this: 
```csharp
[Route("SomeOtherName/{action=Index}")]
public class HomeController : Controller
{
    ...
}
```

Since the new version of ASP.NET 5 changes placeholder for actions from ```{action}``` to ```[action]```,  when I try to use code ```[Route("SomeOtherName/{action=Index}")]```, it tells me "```The attribute route 'SomeOtherName/{action=Index}' cannot contain a parameter named '{action}'. Use '[action]' in the route template to insert the value 'Index'.```".

 And when I try to use ```[Route("SomeOtherName/[action=Index]")]```, it tells me "``` a replacement value for the token 'action=Index' could not be found. Available tokens: 'action, controller'.```".

Is it still possible to use attribute routing on controllers with both an action placeholder and a default value to that action?

**Comment by rynowak** [comment]
This is currently not supported. You'll have to do something like:

```
[Route("SomeOtherName/[action]")]
public class HomeController : Controller
{
    [Route("~/SomeOtherName")]
    [Route("~/SomeOtherName/Index")]
    public void Index()
    {
    }
}
```

See: https://github.com/aspnet/Mvc/issues/3286

**Comment by srayuws** [comment]
Thansk for the link. Let's close this issue since there is already a backlog in the MVC repo.

A suggestion is to have a ONE place to find all the backlogs and known issues, just like the Announce repo for breaking changes, rather than search every repo that might be related.

**Comment by rizwanse** [comment]
**I modified the code a bit here:**
[RoutePrefix("Home")]
[Route("{action}")]
public class HomeController : Controller
{
      [Route("~/")]            // GET /
      [Route]                     // GET /Home
      [Route("Index")]       // GET /Home/Index
      public ActionResult Index() => View();
 }
