### ISSUE TITLE
Throw a nicer error when the routing services haven't been added to DI

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Routing#276]
Like [other parts of the framework](https://github.com/aspnet/SignalR-Server/blob/da96c1d9abae49e6aadeefd30942ad0269a65996/src/Microsoft.AspNet.SignalR.Server/Hosting/BuilderExtensions.cs#L93) we should throw a nice helper exception when services are missing from DI, including the sample call the app needs to add the routing services to DI, e.g.
```
Routing services have not been registered. Register services by calling 'IServices.UseRouting()'.
```

**Comment by DamianEdwards** [comment]
@rynowak @Eilon

**Comment by Eilon** [comment]
MVC already does this. We can follow the same model.

**Comment by rynowak** [comment]
Can we not follow the same model instead? It would be nice to do this on Startup instead of on first request

**Comment by Eilon** [comment]
Hmm ok, do we have an idea of how to do that?

**Comment by rynowak** [comment]
We can register a marker service and have the routing middleware resolve it when created.

**Comment by DamianEdwards** [comment]
Ya, the code linked to above does this.

**Comment by rynowak** [comment]
MVC does it on first request - we should think about changing it to do it when we add AddMvc.

**Comment by Eilon** [comment]
@javiercn you got that? Let's add this to Routing, and then also change MVC to do the same. I logged https://github.com/aspnet/Mvc/issues/3907 and assigned to you.

**Comment by javiercn** [comment]
@Eilon will do it for routing and mvc
