### ISSUE TITLE
Save an allocation of Dictionary in RouteBase.MergeValues

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/Routing#282]
MergeValues copies the values from a source dictionary to destination dictionary. It always creates a new destination dictionary and inserts the source key and values. If the destination dictionary is empty, we can use source as destination rather than allocating a new dictionary for the destination. This will save 1 dictionary allocation per request to ASP.NET MVC . Below is the profile call stack for the allocation
![capture_allocation1](https://cloud.githubusercontent.com/assets/8011073/13024880/060699ea-d1b1-11e5-92bb-2930cdf2cbf9.jpg)

and below is the suggested change

private static void MergeValues(
            RouteValueDictionary destination,
            RouteValueDictionary values)
        {
          <b>  if(destination.Count == 0) 
            {
                destination = values;
            } </b>
         else
            {
                foreach (var kvp in values)
                {
                    // This will replace the original value for the specified key.
                    // Values from the matched route will take preference over previous
                    // data in the route context.
                    destination[kvp.Key] = kvp.Value;
                }
            }

**Comment by Eilon** [comment]
cc @rynowak 

Some questions:
1. Has this shown to be significant in profiles?
2. Are the dictionaries not expected to mutate? My general concern about copying the reference is that mutating the original will mutate both. (I doubt that is a concern here, but I don't know the code.)

**Comment by rynowak** [comment]
>Has this shown to be significant in profiles?

This is 1 dictionary per request. For the kinds of scenarios we're looking at now it's pretty low priority. A good fix is more complex than what's detailed here. The above would optimize away an "empty" dictionary that hasn't had any internal data structures allocated. A better fix would be to have the matcher put it's values directly into `RouteData.Values` and elide a "full" dictionary.

> Are the dictionaries not expected to mutate? My general concern about copying the reference is that mutating the original will mutate both. (I doubt that is a concern here, but I don't know the code.)

This isn't really a concern. It's already protected by the snapshotting we do on `RouteData.

I'd recommend backlog. If we see routing used in more micro-scenarios we could always pull this back.

**Comment by Eilon** [comment]
Moved to Backlog.
