### ISSUE TITLE
Add doc comments for service collection extension methods

### ISSUE THREAD

**Issue by Eilon** [aspnet/Routing#284]
The class and methods here need new/better doc comments: https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/DependencyInjection/RoutingServiceCollectionExtensions.cs

Recommend following the general pattern we've used in other places, e.g. https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs

**Comment by kichalla** [comment]
05ff447d7da7fdf46a6b994e1797a8aaea525c14
