### ISSUE TITLE
Unable to create a route template with query string / question mark

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Routing#285]
I'd like to use the TemplateParser for parsing template like this one : 
'/api/myresource/{resource_id}/?q={query}'

I have the following error : "The literal section '?q=' is invalid. Literal sections cannot contain the '?' character."

Is it by design ?

**Comment by Eilon** [comment]
Yes, it is by design. The current design of routing is that it parses only the "path" segment of the URL. The query part is generally processed by MVC.

You could certainly write a custom `IRouter` that parses the URL in a different way, but there aren't built-in features for this.
