### ISSUE TITLE
[Advice] Cross-router UrlHelper feasibility

### ISSUE THREAD

**Issue by Antaris** [aspnet/Routing#289]
Hi Team,

Given that it is now possible to register multiple instances of `RouterMiddleware` with the pipeline, I am looking at the feasibility of accessing route information registered through an lowest-level `IRouter` and surface this elsewhere.

My primary use-case is a custom `IRouter` used to handle database-driven URL links. E.g, here is my Domain model `Link`:

``` csharp
public class Link : EntityBase
{
  public string RelativeUrl { get; set; }

  public int? ParentLinkId { get; set; }

  public int? RedirectLinkId { get; set; }

  public string LinkHandlerType { get; set; }
}
```

In memory, I formulate my `Link` instances in a tree structure called a `LinkTree` (+`LinkTreeNode`), and this allows me to (on-demand) resolve a link in the tree, and it it doesn't exist, I can lookup the link based on relative URL, and cache the `Link` in the tree for future requests. The `LinkTree` is evented and responds to calls to refresh/invalidate the node and its children based on URL changes driven from the CMS.

This is all handled through a custom `IRouter`, my `LinkRouter` which maintains the `LinkTree` for the current tenant.

The tricky part comes when we have matched a `Link` instance, and we use the `LinkHandlerType` to determine how the link is processed (is it a page, folder, media item etc.). The link handler type _may_ end up delegating back to the `MvcRouteHandler` if the link type supports it.

So, given my app startup:

``` csharp
app.UseMvc(r => { /* MVC specific things */ });
app.UseMiddleware<RouterMiddleware>(new LinkRouter());
```

The call to `app.UseMvc` registers my MVC routes in isolation. The latter call adds an instance of `RouterMiddleware` to the pipeline and adds a custom router.

Now, given that a link handler type could forward to the request to MVC, it would do something similar to this:

``` csharp
public async Task HandleAsync(RouteContext context, Link link)
{
  context.RouteData.Values.Add("controller", "Pages");
  context.RouteData.Values.Add("action", "Display");
  context.RouteData.Values.Add("link", link);

  var router = new MvcRouteHandler();
  await router.RouteAsync(context);
}
```

> This is very naïve, I haven't actually tested this yet

This setup allows me to dynamically manage URLs and dispatch them to an appropriate router at runtime.

The area I am coming unstuck is how to use the `UrlHelper` type from this style of delegated-to-mvc routing, and this is because the `UrlHelper` gets the base `IRouter` from the first instance registered in `RouteData.Routers`. This is of course configured in the `RouterMiddleware`:

https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/RouterMiddleware.cs#L31

``` csharp
var context = new RouteContext(httpContext);
context.RouteData.Routers.Add(_router);
```

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelper.cs#L40

``` csharp
public IRouter Router => ActionContext.RouteData.Routers[0];
```

I understand why this is flowed this way, but this ties the `UrlHelper` to only work when the first `IRouter` in the chain is that registered with MVC, which is a totally fair approach. 

If it is in fact the `LinkRouter` that handles the route (not the `RouteCollection` registered by MVC), then the first `IRouter` is the `LinkRouter` and therefore we can't generate MVC-style links with say `Url.Action` because that exact instance of `UrlHelper` is not using the route collection. Does that make sense?

As an alternative, would it be possible to define a singleton collection for the entire app that allows us to refer to a lowest-level `IRouter` by key, e.g.:

``` csharp
public interface IKeyedRouterCollection
{
  void Add(RouterKey key, IRouter router);

  IRouter Get(RouterKey key);
}

public struct RouterKey
{
  public string Value { get; set; }
}
```

That way, the `RouterMiddleware` could accept a router key argument:

``` csharp
public RouterMiddleware(RequestDelegate next, ILoggerFactory factory, IKeyedRouterCollection routers, IRouter router, RouterKey key)
{
  routers.Add(key, router);
}
```

That way the `UrlHelper` could surface the specific `IRouter` using that same `IKeyedRouterCollection`:

``` csharp
public IRouter Router => ActionContext.HttpContext.RequestServices.GetService<IKeyedRouterCollection>().Get(<router-key>);
```

This would allow the `UrlHelper` to use the router in the scope of MVC, but indirectly from another router.

Does this make sense?

**Comment by Antaris** [comment]
Just developing on this a bit further, perhaps this can be simiplied using the existing `INamedRouter` interface instead:

```csharp
public interface IRouteCollection : INamedRouter
{

}

public class RouteCollection : IRouteCollection
{
  public RouteCollection(string name = null)
  {
    Name = name;
  }
  
  // Code ommited for brevity
}
```

Still not sure about doing the grunt work in a constructor here, but don't currently have a better alternative.

```csharp
public RouterMiddleware(
  RequestDelegate next,
  ILoggerFactory loggerFactory,
  INamedRouterCollection routers,
  IRouter router)
{
  _next = next;
  _router = router;
  
  _logger = loggerFactory.CreateLogger<RouterMiddleware>();
  
  var named = router as INamedRouter;
  if (!string.IsNullOrEmpty(named?.Name))
  {
    routers.Add(named.Name, router);
  }
}
```

**Comment by Antaris** [comment]
@eilon @rynowak @pranavkm 

Any thoughts on this issue?

**Comment by Eilon** [comment]
Hi @Antaris , sorry for the delay. We reviewed this item and we're not entirely sure we understand what the scenario is. Can you give a specific example of what an application would be doing where this feature would be useful?

**Comment by Antaris** [comment]
Hi,

Yeah, it's quite a confusing scenario to succinctly explain, I'll try again, but with diagrams! and a sample RC1 repo (https://github.com/Antaris/IRouterIssue) to hopefully support it.

So here is the most common routing pattern for MVC:

![](http://i.imgur.com/LpHWNCg.png)

Request hits the `RouterMiddleware` configured by MVC, gets accepted by the `RouteCollection`. An instance of `MvcRouteHandler` is used to invoke the Controller/Action.

At this point, the `UrlHelper` that is created for the request utilises `RouteData.Routers[0]` as its source router for URL generation. For the common route, this is the `RouteCollection` instance.

Now, what if I had this:

![](http://i.imgur.com/9RzDswt.png)

My custom middleware instance, again using `RouterMiddleware` uses a custom router, `CustomRouter`. All this router does is this:

```
    public class CustomRouter : IRouter
    {
        public VirtualPathData GetVirtualPath(VirtualPathContext context)
        {
            return null; // NOOP
        }

        public Task RouteAsync(RouteContext context)
        {
            var handler = new MvcRouteHandler();

            context.RouteData.Values.Add("controller", "Home");
            context.RouteData.Values.Add("action", "Index");

            return handler.RouteAsync(context);
        }
    }
```

Now the `UrlHelper` instance, again using `RouteData.Routers[0]` as the source router for URL generation gets my `CustomRouter` instance, instead of MVC's `RouteCollection` instance. Any URLs I try and generate return empty because its impossible for me to get access to the `RouteCollection` registered earlier in the pipeline.

With the example repo, obviously hitting the homepage yields the view with correctly generated URLs for Home, About, etc.

If you instead hit /demo which is launching the same controller/action (home/index), the URLs fail to generate.

My current workaround is having to replicate the body of the `UseMvc` method (as `UseMvcCustom`) so I can correctly capture the `RouteCollection` instance and make that available for use later. This creates a problem that any future updates to MVC may get broken because I've customised the startup code.

I figured a design where we could publish our `IRouter` instances created for the `RouterMiddleware`  *somewhere* allowing us to get hold of them in different scenarios.

Does that make more sense?

This is a very much an edge case, but in my CMS, I've created a custom `LinkTree` (as described above) which allows me to register `Link` instances with a database, where those links could do *anything*, including delegating back to MVC for processing. Or they could simply show a CMS page, etc.

**Comment by Antaris** [comment]
Better yet, instead of having a dictionary to store the `IRouter` instances, could MVC instead perhaps flow the `RouteCollection` as an `HttpContext` feature?

**Comment by Eilon** [comment]
@Antaris sorry for the long delay. I do now understand your scenario - it makes perfect sense to me. It's not something that we plan on addressing at this time as a first-class feature, so at this time you'll need to stick with your custom-built solution. I'm putting this item in the backlog to see if others can chime in on their scenarios, and so that we can consider revisiting in the future.

Also cc @sebastienros who works on Orchard (which is also a CMS) in case he has run into this or similar scenarios.
