### ISSUE TITLE
Revisit service location in Routing...

### ISSUE THREAD

**Issue by HaoK** [aspnet/Routing#292]
Not sure there's any easy fixes for these, but there aren't that many...

Microsoft.AspNetCore.Routing\RouteBase.cs:249:
`var urlEncoder = context.RequestServices.GetRequiredService<UrlEncoder>();`

Microsoft.AspNetCore.Routing\RouteBase.cs:250:
`var pool = context.RequestServices.GetRequiredService<ObjectPool<UriBuildingContext>>();`

Microsoft.AspNetCore.Routing\RouteBase.cs:259:
`var factory = context.RequestServices.GetRequiredService<ILoggerFactory>();`

Microsoft.AspNetCore.Routing\RouteCollection.cs:176:
`_options = context.RequestServices.GetRequiredService<IOptions<RouteOptions>>().Value;`

**Comment by rynowak** [comment]
The issue here is that these classes need to be constructable, yet they also need stuff. These resolves happen once per-route-per app and then are cached.

**Comment by Eilon** [comment]
Yeah Routes (and thus RouteBase) don't themselves come from DI...
