### ISSUE TITLE
Custom route constraint with variable number of arguments

### ISSUE THREAD

**Issue by fredgate** [aspnet/Routing#296]
I am creating custom route constraints. It works perfectly except for one that accepts an undefined number of string parameters in its constructor.

I looked source code of HttpMethodRouteConstraint at https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Constraints/HttpMethodRouteConstraint.cs and reprocued it for mine :
```
public class MyRouteConstraint : IRouteConstraint
{
        public MyRouteConstraint(params String[] values)
        { ... }
}
```

But when I use it in the route of an action
````
[HttpGet("{id:my(foo,bar)}")]
````

an exception occurs at runtime
````
System.InvalidCastException: Cast non valide de 'System.String' en 'System.String[]'.
   à System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   à System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   à System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   à Microsoft.AspNet.Routing.DefaultInlineConstraintResolver.ConvertArguments(ParameterInfo[]
````

I don't know where the constraints are instantiated, but it seems that _params_ is not really supported for inline constraints.

**Comment by Eilon** [comment]
At this time, *inline* route constraints (the ones you specify within the route template pattern) support having either only a single `string` parameter, or multiple parameters that are separated by commas. Constraints can also be used as part of the `constraints` parameter you can pass into a route definition, in which case you `new` up the constraint yourself and pass in whatever constructor parameters you want.

To write an *inline* constraint that takes multiple parameters, you can either:
1. Have multiple parameters of simple types (string, int, bool, etc.)
2. Take a single `string` parameter and then parse it however you want (e.g. split on every `,` or whatever).

Example of a multi-parameter constraint: https://github.com/aspnet/Routing/blob/70d674410e8ba3d91e427ffd3ed09564f2e2d394/src/Microsoft.AspNetCore.Routing/Constraints/RangeRouteConstraint.cs#L21

Code that does all the parsing: https://github.com/aspnet/Routing/blob/70d674410e8ba3d91e427ffd3ed09564f2e2d394/src/Microsoft.AspNetCore.Routing/DefaultInlineConstraintResolver.cs
