### ISSUE TITLE
Explicit set the namespace used for controller

### ISSUE THREAD

**Issue by seriouz** [aspnet/Routing#302]
Hello Guys,

is there a way to set the namespace which will be used for a route specified by a special prefix?
I think something like this would be very useful:

The default sites are aquired with
```csharp
routes.MapRoute(
                name: "Default",
                template: "{controller}/{action}/{id?}",
                defaults: new { controller = "Home", action = "Index" }
             );
```
but then in the Controllers folder there is another folder "Acp" with its own HomeController.cs. It could be targeted with
```csharp
routes.MapRoute(
                name: "Acp",
                template: "acp/{controller}/{action}/{id?}",
                defaults: new { controller = "Home", action = "Index" },
                namespace: "MyProject.Controllers.Acp"
             );
```

**Comment by rynowak** [comment]
You can do this with conventions, we have a sample that does something very similar. https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention
