### ISSUE TITLE
Routes with custom route template parameter does not resolve correctly across areas

### ISSUE THREAD

**Issue by rmja** [aspnet/Routing#307]
I am configuring the following routes:

```
app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "defaultWithManufacturerAndId",
                    template: "{area:exists}/{manufacturer}/{controller}/{action}/{id}");

                routes.MapRoute(
                    name: "defaultWithManufacturer",
                    template: "{area:exists}/{manufacturer}/{controller}/{action=Index}");

                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}");
            });
```

The `manufacturer` is an argument that is required in the route template. When generating links with the https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/AnchorTagHelper.cs which crosses the area boundary, then the correct route is not picked up when generating the link:

For example, when activating the following route: http://localhost:5000/Sales/Audi/Products,
and inserting the following link:

```
<a asp-action="Index" asp-controller="Tickets" asp-route-area="Support">Go to support tickets (in different area) (Broken link)</a>
```

The expected behavior would be that, because the link is inserted in a view where `manufacturer` is defined, that the link would be generated with the `defaultWithManufacturer` template. But the route picked up is the `default` and so the link becomes: http://localhost:5000/Tickets?area=Support.

Note that it works if the area is not changed, so the following link works:
```
<a asp-action="Details" asp-route-id="1337">Go to product details (in same area) (Working link)</a>
```
which correctly resolves to http://localhost:5000/Sales/Audi/Products/Details/1337

latest rc2 bits and repro https://github.com/rmja/RoutingExample

**Comment by javiercn** [comment]
It took me a while but I think I know what's happening.
Your template is "{area:exists}/{manufacturer}/{controller}/{action}/{id}" so the ambient values that you have are 

```
area=Sales, manufacturer=Audi, controller=Products, action=Index, id=1337
```

The second template that

```
<a asp-action="Index" asp-controller="Tickets" asp-route-area="Support">Go to support tickets (in different area) (Broken link)</a>
```

targets is

```
"{area:exists}/{manufacturer}/{controller}/{action=Index}"
```

Given that the area is explicitly specified through asp-area, the other ambient values to the right are not taken into account. So given the route does not have a default value for manufacturer it fails to generate a link and then the next route which can generate the link generates it.

If you provide a default value to manufacturer you'll see that the link that gets generated is /Support

@rynowak is this correct?

**Comment by rmja** [comment]
@javiercn year, but should the ambient values not be used to select the route even when the controller is explicitly specified? Otherwise, I would have to set a default value for `manufacturer`, even though there is no default, just to get the route selected. But would it then be populated witht the actual ambient values?

**Comment by javiercn** [comment]
@rmja The reason why the ambient values are not preserved is because you are specifying the area (a parameter in the left of the template) to a different value than the current one. Conventional routes are "hierarchical" in the sense that ambient values are only used as long as all the values for parameters to the left are not specified or have the same value. By changing the value of a parameter on the left (area) we assume that all remaining ambient values are not valid. This has been the behavior of MVC since v1.0.

**Comment by rmja** [comment]
@javiercn phew, I finally got it😀
