### ISSUE TITLE
Should GetVirtualPath return PathString

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#31]
Inside URL generation in MVC we need to do some stuff that PathString already handles. Would be easier if GetVirtualPath just returned PathString.

We have to harden this code against a missing leading slash because 3rd party route code could do it. Using PathString would enforce this.

```
            var context = new VirtualPathContext(_httpContext, _ambientValues, values);

            var path = _router.GetVirtualPath(context);

            PathString pathString;
            if (path.Length > 0 && !path.StartsWith("/", StringComparison.Ordinal))
            {
                pathString = new PathString("/" + path);
            }
            else
            {
                pathString = new PathString(path);
            }

            return _httpContext.Request.PathBase.Add(pathString).Value;

```

**Comment by ianhong** [comment]
@rynowak 
Just to make sure I'm working on #158 to add VirtualPathData and make GetVirtualPath to return an object of it.

public class VirtualDataPath
{
..
        public string VirtualPath        {           get;set        }
}
So, we want to change the type of VirtualPath from string to PathString??

**Comment by rynowak** [comment]
Yes, that's the change :+1:. Hopefully there's not too much test impact here since it has a conversion to string.

**Comment by ianhong** [comment]
ff209f04bb2daded5ae49fae015b6631d8a861d0
