### ISSUE TITLE
Optional route constraint not working when before [controller] placeholder

### ISSUE THREAD

**Issue by TsengSR** [aspnet/Routing#312]
I got a bit of little challange getting routes working the way I'd like. Basically, I want to have a locale/culture as part of the url path rather than the currently provided query parameter, cookie or accepted language header.

So I made a constraint for it, which is working so far. 

```
    public class LocaleConstraint : IRouteConstraint
    {
        private static readonly Regex LocalePattern = new Regex(@"^[a-z]{2}(-[a-z]{2,4})?$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

        public bool Match(HttpContext httpContext, IRouter route, string routeKey, IDictionary<string, object> values, RouteDirection routeDirection)
        {
            if (!values.ContainsKey(routeKey))
                return false;

            string locale = values[routeKey] as string;
            if (string.IsNullOrWhiteSpace(locale))
                return false;

            return LocalePattern.IsMatch(locale);
        }
    }
```

Then I create an route via attributes on the controller

```
[Route("api/{culture:locale}/[controller]")]
public class ExampleController : Controller 
{
    ...
}
```

Works well so far. But it only works when I access it via `/api/en-US/exampe/` url. `/api/exampe` is not working. I tried `"api/{culture:locale?}/[controller]"` and `"api/{culture:locale=en-US}/[controller]"`, but none of them matches `/api/example`.

Of course it works, when I add both routes to the controller.

```
[Route("api/[controller]")]
[Route("api/{culture:locale}/[controller]")]
public class ExampleController : Controller 
{
    ...
}
```

While this works, it has some nasty side effects. I use Swashbuckle Swagger for API documentation and it will generate all routes double, which is pretty annoying. 

Is there any way to get the optional parameter working on the `culture` url parameter? I can get it, if this doesn't work as a general route defined in Startup.cs (because controller is not know at this time), but when using attribute routing the [controller] is being replaced with the controller name when doing the registrations, so to my understanding optional parameters before the `[controller]` placeholder shouldn't be a problem. 

Is this a bug?

**Comment by Eilon** [comment]
@TsengSR the "optional route segment" feature works only if it is the last segment, or followed by other optional segments.

So these work:

```
"{req1}/{opt1?}"
"{req1}/{opt1?}/{opt2?}"
"{req1}/segment1/{opt1?}"
"{req1}/segment1/{opt1?}/{opt2?}"
```

But these do not:
```
"{req1}/{opt1?}/segment2"
"{req1}/{opt1?}/segment2/{opt2?}"
"{req1}/segment1/{opt1?}/segment2"
"{req1}/segment1/{opt1?}/segment2/{opt2?}"
```

The workaround you have done is exactly what we recommend: add additional routes that omit the non-optional segments.

BTW the reasoning for this restriction is simple: what does it mean for an optional segment to exist in the middle of a route? Can it be omitted and the rest of the URL omitted as well? Or can it be omitted but you have to have the rest of the URL still present? We believe that it would be more difficult to understand due to the ambiguities that it would create.
