### ISSUE TITLE
Use a tilde (~) on the method attribute to override the route prefix does not work if not followed by a slash (/)

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Routing#320]
As can be read here:
http://www.asp.net/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2
The proper way to break out of the route prefix set at controller level for instance is to prepend the route with a tilde.

However not following this tilde with a slash does not work and the request ends up in another action.

This works (simplified):
```cs
[Route("api/v1/[controller]")]
public class CommentsController {
    [HttpGet("~/api/v1/pages/{id:int}/[controller]")]
    public Task<IEnumerable<Model>> GetMany(...) { ... }
}

[Route("api/v1/[controller]")]
public class PagesController {
    [HttpGet("{ptSlug}/{slug}")]
    public Task<Model> GetByPath(...) { ... }
}
```
(Take note of the subresource literal route GetMany which overlaps with GetByPath)
A call to `/api/v1/pages/123/comments` correctly ends up in GetMany
However changing the GetMany route to:
```cs
[HttpGet("~api/v1/pages/{id:int}/[controller]")]
```
Kills the joy and the request will now end up in GetByPath.

**Comment by javiercn** [comment]
I believe you need to use just '/' in ASP.NET Core. Let me know if that doesn't work

**Comment by javiercn** [comment]
So ```/api/v1/pages/{id:int}/[controller]``` in your case

**Comment by NinoFloris** [comment]
Ahh oh that explains it ;) and everything before the first slash gets discarded then?

**Comment by javiercn** [comment]
Yes

**Comment by javiercn** [comment]
Hi. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
