### ISSUE TITLE
Add support for chaining handlers to IRouteBuilder

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#321]
We want to add a feature like the following so that user code can 'chain' to arbitrary routes. This is useful for cases where the 'handler' is not `IRouteBuilder.DefaultHandler` - such as MVC attribute routing.

```
app.UseMvc(routes =>
{
    routes.HandlerFactories(next => new MyRouter(next));

    ...
});
```

```
public interface IRouteBuilder
{
    IList<Func<IRouter, IRouter>> HandlerFactories { get; }

    ...
}

public static class RouteBuilderExtensions
{
    // IApplicationBuilder-like chaining
    public static IRouter CreateHandler(this IRouteBuilder routeBuilder, IRouter next)
    {
        for (var i = routeBuilder.HandlerFactories.Count - i; i >= 0; i--)
        {
            next = routeBuilder.HandlerFactories[i](next);
        }

        return next;
    }
}
```

Code like `MapRoute` would call `CreateHandler(routeBuilder.DefaultHandler)` to create the rest of the chain. Code like MVC attribute routing would call `CreateHandler(handler)` for each handler it needs to create.

**Comment by Eilon** [comment]
@rynowak any thoughts on the priority of this? What would make us want to implement this?

**Comment by rynowak** [comment]
I think user-demand would raise the priority of this. We made some late changes to 1.0.0 in this area and took away a "feature" that acts a lot like a delegating handler.

So far there haven't been any concrete asks for something like this.

**Comment by Eilon** [comment]
Parking in Backlog for now. Will close if we don't hear more on this.
