### ISSUE TITLE
RouteValueDictionary value constructor fails with reflection errors

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Routing#322]
When instantiating a RouteValueDictionary with a list of constraints, I got an exception stating the `Comparer` property `IOrdinalConstraint` needed to be of type `string` or `IRouteConstraint`.

This code fixed the issue

```
var constraints = new RouteValueDictionary();

foreach (var kv in route.Constraints)
{
  constraints[kv.Key] = kv.Value;
}
```

instead of 

```
var constraints = new RouteValueDictionary(route.Contraints);
```

I think that it happens when the constructor is called twice in a raw on constraints. In my case I did it on the result of a call to MapAreaRoute which does that already.

**Comment by rynowak** [comment]
`route.Constraints` isn't a `RouteValueDictionary` (and isn't supposed to be). Unfortunately generics making doing a conversion in all of the possible cases expensive and this is a **super** hot code path in views.

**Comment by sebastienros** [comment]
More context, I am trying to alter the template of an existing route, I do so by creating a new route and trying to copy every property:

```
var prefixedRoute = new Route(
                    _routeBuilder.DefaultHandler,
                    route.Name,
                    routePrefix + route.RouteTemplate,
                    route.Defaults,
                    route.Constraints, // it takes an IDictionary<string, object> but is an IDictionary<string, IRouteConstraint> in the existing route
                    route.DataTokens,
                    _inlineConstraintResolver);
```

Maybe there are no issues with the current code and it's just that trying to use a `RouteValueDictionary` constructor to convert it to an `IDicionaty<string, object>` which is wrong. What is the recommended way to pass constraints across routes ?

**Comment by sebastienros** [comment]
Will just create a new `Dictionary<string, object>` from the `IDictionary<string, IRouteConstraint>` of the original route.
