### ISSUE TITLE
Add an overload of MapRoute which accepts constraints when a request delegate or application builder is used.

### ISSUE THREAD

**Issue by kichalla** [aspnet/Routing#328]
Not sure how much we care about this as it can be achieved by writing an extension by the end user.

Currently we have the following extensions:
![image](https://cloud.githubusercontent.com/assets/6559784/16126065/5b053fc6-33ab-11e6-9707-7c9fa68854f6.png)

Default values could be supplied inline and also the constraints on parameters, but no overload which takes in route level constraints.

**Comment by Eilon** [comment]
Will wait for customer demand.
