### ISSUE TITLE
Consider exposing default routing feature implementation

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Routing#333]
Consider making [RoutingFeature](https://github.com/aspnet/Routing/blob/457cd92bca57c63da418822eab9dad00bde9ceff/src/Microsoft.AspNetCore.Routing/RouterMiddleware.cs#L52) class public, because testing code with `DefaultHttpContext` doesn't give `IRoutingFeature` by default and creating class just for that is kind of pointless.

**Comment by rynowak** [comment]
This is something we can do.

**Comment by rynowak** [comment]
322e1f5d9c7b78c079f9c21b9409416c4b070254
