### ISSUE TITLE
TemplateMatcher.TryMatch sets all route values to strings, even if otherwise specified.

### ISSUE THREAD

**Issue by ConnorMcMahon** [aspnet/Routing#336]
When using the function TryMatch(PathString path, RouteValueDictionary values), on the path "mainpage/5/true" with a template of the form "{countername}/{add:int}/{log:bool}", I would expect the resulting dictionary to look along the lines of { "countername": "mainpage", "add": 5, "log": true}. However, instead I receive a dictionary that looks like {"countername": "mainpage", "add": "5", "log": "true"}, despite the fact that add is specified as an integer and log is specified as a Boolean. 

Since a RouteValueDictionary object's values are of type object, and the TemplateMatcher class has all of the InlineConstraint information inside of it, it seems that the TryMatch function should fill out the values to the appropriate types.

**Comment by javiercn** [comment]
This behavior is by design. The interface is IDictionary<string,object> for historical reasons but it's not the routing job to perform type conversions for the parsed data. Effectively all values are strings inside the dictionary.

/cc @rynowak

**Comment by ConnorMcMahon** [comment]
So then is "images/hello" supposed to match the template "{category}/{id:int}", even though "hello" is not an integer?

**Comment by rynowak** [comment]
Route constraints answer a yes/no question about the format of the text, they don't perform type conversions.

**Comment by Eilon** [comment]
Yup, it's the job of model binding to do the type conversions.
