### ISSUE TITLE
Add overload to MapRoute that takes a custom handler.

### ISSUE THREAD

**Issue by javiercn** [aspnet/Routing#340]
MapRoute provides overloads that allow you to specify constraints, default values, data tokens, etc. but not a route handler to use.

We should add a route that allows you to use a custom route handler instead of the default one.

**Comment by Eilon** [comment]
What code do you have to write today to do it?

**Comment by Eilon** [comment]
Also, in System.Web's Routing, what did it look like?

**Comment by javiercn** [comment]
```C#
            routes.Routes.Add(new Route(
                 target: new RouteHandler(async ctx => await ctx.Response.WriteAsync("yolo")),
                 routeName: "someRoute",
                 routeTemplate: "/api/yolo",
                 constraints: new Dictionary<string, object>(),
                 defaults: new RouteValueDictionary(),
                 inlineConstraintResolver: null,
                 dataTokens: new RouteValueDictionary()));
```

And you need to get the inline constraint resolver from somewhere

**Comment by javiercn** [comment]
I failed to mention that the code above is for ASP.NET Core. Some of the pain points are:
* You need to know about the relationship between Route and RouteHandler (both are IRouter implementations)
* You need to figure out how to build an InlineConstraintResolver (or get it from DI)

**Comment by Eilon** [comment]
Ah, yes, that's quite cumbersome.

What is the scenario for it? We will likely put on backlog until we see specific customer demand for it.
