### ISSUE TITLE
Need support for IsHandled for RouteContext

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [aspnet/Routing#343]
Previously i could get the IsHandled from the RouteContext but i think its been removed from the RC2. Is there any workaround for it?

**Comment by rynowak** [comment]
Routing sets a `RequestDelegate` handler on the `RouteContext` now when a route matches. The handler will be invoked later by the routing middleware.

Depending on what you trying to do you will either want to provide a handler, or invoke the handler.

**Comment by Eilon** [comment]
@rynowak anything further required here? Or just close?

**Comment by rynowak** [comment]
Sorry, I should have tagged this as a question. This should be closed, you still get the same information by checking `Handler != null`
