### ISSUE TITLE
Custom RouteTemplate

### ISSUE THREAD

**Issue by hauteur** [aspnet/Routing#344]
Okay, so to be fair, I'm not sure if this is an issue with the implementation, the documentation, or just with my understanding.

Under RC1, I was playing with using a custom route template to look up virtual URLs from a database and then returning whether or not there was a match.  The way that I found to do that was to use a custom implementation of `RouteTemplate` (then `TemplateRoute`) in a custom `MapRoute` overload because `TemplateRoute` implemented `IRouter` and it had the same constructors.

Under RTM, I am not seeing how to implement a custom route template - even in looking at the source for `MapRoute()` and `Route`.  Am I maybe just missing something simple?

Thanks!

**Comment by rynowak** [comment]
Do you need a custom route for this? Do you need to retrieve new routing information while the app is running? 

If you need to do this, start by implementing `IRouter`, you can use `TemplateBinder` and `TemplateMatcher` classes.

You won't use `MapRoute`, because that will always create an instance of `Route` directly. You can just call `Add` on the route collection.

**Comment by hauteur** [comment]
Thanks for the response.

Technically, I don't know that it is routing information - the controller and action will likely always be the same.  It is basically a CMS, and I need to determine whether the path actually exists or to let it drop to default handling or return a 404.

As far as the `MapRoute` - I'm not calling it again.  I'm calling `Add` from within it.  Because `TemplateRoute` implemented `IRouter`, I was able to get away with it.  Under RTM, it looks like it no longer implements `IRouter`.

I looked at `TemplateBinder` and `TemplateMatcher` and it looks like they both require an instance of `RouteTemplate

**Comment by rynowak** [comment]
`TemplateRoute` was renamed to `Route` https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Route.cs

**Comment by hauteur** [comment]
Thanks for the reply.

That makes sense.  I think what was throwing me is that there is a class called `RouteTemplate` and `Route` doesn't have a `RouteAsync` method.  I'm guessing that it was changed to `OnRouteMatched` then.

I will give that a try.  Thank you so much for your help.

**Comment by rynowak** [comment]
I'm going to close this for now then since I've answered your question. Please reopen or create a new issue if you need anything else :+1:

**Comment by hauteur** [comment]
That's what it was.  Thank you so much!
