### ISSUE TITLE
Need to rewrite/refactor TemplateBinder to reduce RouteValueDictionary allocation

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Routing#348]
Original issue - https://github.com/aspnet/Mvc/issues/4593#issuecomment-218627205

We want to have a cleaner fix than what we have in https://github.com/aspnet/Routing/pull/314

@rynowak @Eilon

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2670
