### ISSUE TITLE
How to Get Route Data from URL

### ISSUE THREAD

**Issue by xaviergxf** [aspnet/Routing#350]
Hi,

   How can i get the route information from a url passed by a parameter into an action of a controller?

Thanks!

**Comment by rynowak** [comment]
Does this do what you want?

```
// Inside a controller
public IActionResult Index()
{
    var value = (string)RouteData.Values["my-value"]
}
```

If not can you provide more info about where your code is running and what you want to do with the data?

**Comment by xaviergxf** [comment]
Hi Ryan,

   Here's an example:

class MyController: Controller{

    [MyAttribute]
    public void Test1()
    {
    }

    public void Test2(string url)
   {
       //let's say url="http://localhost:8642/My/Test1?query=query"
       // I want a function that retrieves Route["Test1"] to be able to use
reflection and get MyAttribute.
   }
}

Thanks

Xavier Eric Moura Klausener
xaviergxf@gmail.com
+41774573651

**Comment by rynowak** [comment]
I'm assuming based on the description that you're using something like the default conventional route `{controller}/{action}/{id?}` - is that right?

In this case, matching the URL `http://localhost:8642/My/Test1?query=query` would produce the route- values `{ action = "My", controller = "Test1" }` so `RouteValues.Values["action"]` would return `"Test1"`. 

Regarding retrieving the attribute, that's just normal reflection code. I still don't understand quite what you're asking and how it's connected to MVC. Can you explain more about what you're trying to accomplish? Usually if you're going to the reflection layer there's already a feature that does what you want.

**Comment by xaviergxf** [comment]
Hi Ryan,

  But doing RouteValues.Values["action"] is to get the current method
"action" value. Is there a function like RouteValues.Parse(url) which
retrieves me route values?

Thanks

Xavier Eric Moura Klausener
xaviergxf@gmail.com
+41774573651

**Comment by rynowak** [comment]
so if I understand correctly you want to parse a URL using the same functionality routing uses? [TemplateMatcher](https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Template/TemplateMatcher.cs) should do what you want

**Comment by xaviergxf** [comment]
Thanks Ryan! I'll test it tomorrow :)

Xavier Eric Moura Klausener
xaviergxf@gmail.com
+41774573651

**Comment by xaviergxf** [comment]
Hi Ryan,

  I tested and managed to make it work. Here's the method if anyone wants to do the same:

`protected RouteValueDictionary GetRouteValuesFromUrlOrReferer(string url = null)
        {
            if (url == null)
            {
                if (!this.HttpContext.Request.Headers.ContainsKey("Referer"))
                    throw new Exception("url parameter not delivered and Referer header is empty");
                url = this.HttpContext.Request.Headers["Referer"].ToString();
            }
            var route = this.RouteData.Routers.OfType<Route>().FirstOrDefault(p => p.Name == Startup.DefaultRouteName);
            var template = route.ParsedTemplate;
            var matcher = new TemplateMatcher(template, route.Defaults);
            var routeValues = new RouteValueDictionary();
            var localPath = (new Uri(url)).LocalPath;
            if (!matcher.TryMatch(localPath, routeValues))
                throw new Exception("Could not identity controller and action");
            return routeValues;
        }`

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
