### ISSUE TITLE
Question: Nested routes

### ISSUE THREAD

**Issue by dodyg** [aspnet/Routing#352]
I expected that '/hello/world' would return "Hello World" but it does not match. What is the correct way to implement a nested route? I read it in the [documentation](https://docs.asp.net/en/latest/fundamentals/routing.html) but it never gives example.

```
   public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRouting();
        }

        public void Configure(IApplicationBuilder app)
        {
            var defaultHandler = new RouteHandler (context =>
            {
                var routeValues = context.GetRouteData().Values;
                return context.Response.WriteAsync($"Route values: {string.Join(", ", routeValues)}");
            });

            var routes = new RouteBuilder(app, defaultHandler);

            routes.MapGet("hello", (IApplicationBuilder app2) =>{
                var routes2 = new RouteBuilder(app2);
                routes2.MapGet("world", (context) => context.Response.WriteAsync("Hello World"));
                app2.UseRouter(routes2.Build());
            });

            routes.MapRoute(
                name: "Default", 
                template: "{*path}"
            );

            IRouter routing = routes.Build();
            app.UseRouter(routing);
        }
    }
```

**Comment by Eilon** [comment]
@kichalla can you figure out why this isn't working? At a glance, it seems like it should...

**Comment by rynowak** [comment]
This won't work because nothing in the system 'chops' the path on `HttpContext.Request.Path`. When the second route runs the path is still set to `/hello/world`. 

We built an example (not a full sample) of what you would need to do: https://github.com/aspnet/Routing/blob/dev/samples/RoutingSample.Web/PrefixRoute.cs

**Comment by Eilon** [comment]
Oh, I thought that the `MapXyz` methods trim the start and treat it as a PathBase, and the Path ends up having the "remainder." So that's not the case?

cc @Tratcher

**Comment by Eilon** [comment]
Oh wait I just realized that this is MapGet, not the "core" Map APIs. Do they all behave the same? Or do some work one way, and the others another way?

**Comment by Tratcher** [comment]
@Eilon  you're thinking of IApplicationBuilder.Map(PathString,...). Not sure what MapGet does.

**Comment by rynowak** [comment]
Yep. Nothing in routing does this.

**Comment by Eilon** [comment]
Oh duhhhhhh, every time I look at the code I see something new 😄 None of this is IApplicationBuilder at all!

So, this is by design.
