### ISSUE TITLE
Fix behavior when optional parameters are defined within a route and not at the end

### ISSUE THREAD

**Issue by javiercn** [aspnet/Routing#357]
https://github.com/aspnet/Routing/issues/326

We create the incorrect tree. We should remove the optionality for route matching when we create the attribute route tree.

**Comment by javiercn** [comment]
After doing some further investigation the E2E behavior is expected here. The optional parameter will be ignored during route matching. And for route generation it will only be considered as a default value. So for example, given the template

```/a/b/{c=3}/d```
It will only match routes like
```/a/b/c/d```
```/a/b/e/d```

and at link generation time, it will generate the route
```/a/b/3/d```

The reason for this to happen is that while TreeRouteBuilder creates the incorrect tree, TemplateRouteMatcher actually checks all the segments in the template and fails to match requests like /a/b when it gets to the d segment and determines that its not optional.

Given that the current behavior is what we expected the fix for this bug to be, we don't have to do anything here other than add the relevant tests to document the behavior here.

**Comment by javiercn** [comment]
@rynowak @Eilon

**Comment by rynowak** [comment]
I don't get what you're saying - are you saying that the behavior in 1.0.0 is correct or incorrect?

**Comment by Eilon** [comment]
I think this bug just needs to be closed, no?

**Comment by javiercn** [comment]
@rynowak still wants to fix the behavior on treeroutebuilder.

**Comment by rynowak** [comment]
We build the wrong data structure, and then rely on the implementation details of another part of the code to bail us out.

**Comment by Eilon** [comment]
Well that sounds just dandy 😄 Indeed, let's clean that up... And we're sure we have enough test coverage for this now?
