### ISSUE TITLE
Routing is matching empty segments to parameters and defaults are wrong

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#359]
Consider the following:
```
    public class ValuesController : Controller
    {
        [HttpGet("{a=a}/{b=b}/{c=c}")]
        public string Get(string a, string b, string c)
        {
            return $"{a} - {b} - {c}";
        }
    }
```

This should match a url like `/` or `/10` or `/10/20` or `/10/20/30` 

However with a URL like `///hi` this will match. And the output will be `b - c - hi`. That is, the parameter `a` gets the default value `b` and is able to match an empty string.

**Comment by Eilon** [comment]
Let's add like a million tests for these cases...

**Comment by Eilon** [comment]
Done?
