### ISSUE TITLE
Slashes incorrectly encoded when building URL with catchall param?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Routing#363]
Consider this controller:

``` csharp
public class TestController : Controller
{
  [Route("foo/{*path}")]
  public IActionResult Index(string path)
  {
    var url = Url.Action("Index", new { path = "hello/world" });
    return Content("Path = [" + path + "], built URL = " + url);
  }
}
```

When you hit `http://example.com/foo/some/url`, ASP.NET MVC Core will display:

```
Path = [some/url], built URL = /foo/hello%2Fworld
```

Whereas ASP.NET MVC 5 will display:

```
Path = [some/url], built URL = /foo/hello/world
```

Notice that the URL returned by `Url.Action` encodes `/` as `%2F`, whereas the previous MVC version did not do this.

Is this an expected change? If so, how do I render the URL such that the slash is **not** encoded?

**Comment by SonicGD** [comment]
Have same problem right now. Any news on this? @Daniel15, did you bypass it somehow?

**Comment by Daniel15** [comment]
I never got time to look into it, these routes on my site are still broken 😞

**Comment by SonicGD** [comment]
So i did some investigation... Character encoding happens in https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Internal/UriBuildingContext.cs#L100

and UrlEncoder always filters '/' char - https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/UrlEncoder.cs#L125

I don't see any way to configure or disable this behavior.

Maybe @NTaylorMullen or @rynowak will help us?

**Comment by SonicGD** [comment]
Also, even if i generate correct url - i doesn't match route. ex:

```csharp
[HttpGet("/{parentUrl}/files/{catPath}/{fileName}.html")
```
where `catPath` is path like 'video/others'.

Only workaround i found is to use catchall param and then parse it with regex. And it looks ugly :cry:

**Comment by DeadSith** [comment]
The only way to bypass it now is to set urls in a tags using href, not built-in tag helpers. It makes it harder to refactor code, but at least you get good-looking urls.

**Comment by Daniel15** [comment]
This is still broken :(

I worked around it by using `Url.Action` then calling `.Replace("%2F", "/")` on the resulting string. Ugly but it works: https://github.com/Daniel15/Website/commit/26b1d2ad8c307afda07d70769265ea71ce775d2c

**Comment by DamianEdwards** [comment]
@rynowak @Eilon comments?

**Comment by Eilon** [comment]
We'll see if we can take another look at this. The problem, if I recall, isn't so much with how to encode slashes, but rather what to do when they come back in. I believe that servers/reverse-proxies such as IIS (and no doubt others) will *decode* the slashes on the way in, so you don't get round-tripping of data. We spent a lot of time back in MVC 1.x-5.x trying to make this work and never could. It's possible that today things are different.

**Comment by Daniel15** [comment]
> I believe that servers/reverse-proxies such as IIS (and no doubt others) will decode the slashes on the way in

Why would the slashes be encoded in the first place? If I have a route like `foo/{*path}`, hitting `/foo/bar/baz` is a valid path. I never had issues with that in older ASP.NET MVC versions, other than IIS6 which is not really a problem these days.

**Comment by Eilon** [comment]
I believe that an incoming URL in the form `http://localhost/foo/bar` is *different* from `http://localhost/foo%2fbar`. The first URL has a path with two segments: `foo` and `bar`. The second URL has a path with one segment: `foo/bar` (once it's decoded).

**Comment by kaa** [comment]
Arguably, if it was a "normal" path segment, but this is specifically a "catch all" path segment which by its nature is going to contain slashes in unencoded form. For a normal path segment the current implementation is the expected behavior of course.

Currently there is no way to create an url using the UrlHelper that fits your first form, as far as I understand. This is what we're asking for.

**Comment by Daniel15** [comment]
Yeah, @Eilon  I should have clarified that this is a catchall segment, so it should capture everything including slashes. 

The actual routing is working fine, it's just the URL builder that's incorrectly HTML encoding the slashes.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2669
