### ISSUE TITLE
Improvements to MapVerb and friends...

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Routing#364]
They're close to being useful, but I feel like they are still limited in application.  What is needed is a way to define a name, the template, the controller and the action without having to resort to the anonymous types every time.

Right now in one of my projects, I define a set of extension methods as follows:

```
        public static IRouteBuilder Get(
            this IRouteBuilder routes,
            string path,
            string controller,
            string action,
            string name,
            object constraints = null
        ) {
            return routes.AddVerb("GET", path, controller, action, name, constraints);
        }
```

My `AddVerb` is similar in intention to `MapVerb`, except that it uses `MapRoute` so that I can gain the benefit of route names:

```
        private static IRouteBuilder AddVerb(
            this IRouteBuilder routes,
            string httpMethod,
            string path,
            string controller,
            string action,
            string name,
            object constraints = null,
            object defaults = null
        ) {

            if(defaults == null)
                defaults = new {
                    controller,
                    action,
                };

            if(constraints == null)
                constraints = new RouteValueDictionary(new {
                    httpMethod = new HttpMethodRouteConstraint(httpMethod)
                });

            return routes.MapRoute(name, path, defaults, constraints);

        }
```

What's missing here compared to [`MapVerb`](https://github.com/aspnet/Routing/blob/1.0.0/src/Microsoft.AspNetCore.Routing/RequestDelegateRouteBuilderExtensions.cs#L156-L180) is:

 - I can still pass a `controller` and `action` rather than a `RequestDelegate`
 - I can still name the route

I'm not sure if this is because the `Map*` series is an abstraction at the middleware level and `MapRoute` is an abstraction at the MVC level.  But I've campaigned in the past ([1](https://github.com/aspnet/Routing/issues/235), [2](https://github.com/aspnet/Mvc/issues/2486)) for [a better API for route declaration](https://laravel.com/docs/5.3/routing).  I think this is still an area where ASP.net Core can improve greatly.

High level suggestions would be

 - Do not rely on conventions
 - Do not force people to use attributes
 - Do not rely on areas to influence application surface area
 - Better documentation ;)

**Comment by davidfowl** [comment]
This belongs in MVC not routing.

**Comment by atrauzzi** [comment]
One day, I'm going to know all the right repositories. :)
