### ISSUE TITLE
Add extensions for super simple HTTP service application building

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Routing#367]
Some people want to have as little code as possible in a single file (`Program.cs`) to stand up very simple HTTP services (no, I won't say "micro-services").

In other platforms (Go, Node, etc.) it's generally very easy to get an HTTP server up with some basic dispatching to various request-handling functions based on URL path. Doing this in ASP.NET Core today requires slightly more ceremony (Using `IApplicationBuilder`, `RouteBuilder`, a `Startup` class, etc.) but this can be very easily fixed with a couple of new extension methods in Routing.

Super simple HTTP service application:

``` c#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace NotAMicroService
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseUrls("http://+:8080/") // optional, we default to listening on http://localhost:5000/
                .Configure(app => app
                    .UseRouter(router => router
                        .MapGet("hello/{*name}", (req, res, data) => res.WriteAsync($"Hello, {data.Values["name"]}!"))
                        .MapGet("goodbye/{*name}", (req, res, data) => res.WriteAsync($"Goodbye, {data.Values["name"]}!"))
                        .MapGet("{*name}", (req, res, data) => res.WriteAsync($"Welcome, {data.Values["name"]}!"))
                    )
                )
                .Build();

            host.Run();
        }
    }
}
```

Extension methods we need to add to `Microsoft.AspNetCore.Routing` to make this work:

``` c#
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;

namespace Microsoft.AspNetCore.Hosting
{
    public static class WebHostExtensions
    {
        public static IWebHostBuilder UseRouter(this IWebHostBuilder builder, Action<RouteBuilder> routeBuilder)
        {
            return builder
                .ConfigureServices(services => services.AddRouting())
                .Configure(app =>
                {
                    var router = new RouteBuilder(app);
                    routeBuilder(router);
                    app.UseRouter(router.Build());
                });
        }
    }
}
```

``` c#
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace Microsoft.AspNetCore.Hosting
{
    public static class RouteBuilderExtensions
    {
        public static IRouteBuilder MapGet(this IRouteBuilder builder, string template, Func<HttpRequest, HttpResponse, RouteData, Task> handler)
        {
            builder.MapGet(template, context =>
            {
                return handler(context.Request, context.Response, context.GetRouteData());
            });
            return builder;
        }
    }
}
```

**Comment by dustinmoris** [comment]
Hey, I saw this watching yesterday's standup today and think this is a brilliant idea. Can I suggest to add an overload which defines the handler as `Func<HttpContext, RouteData, Task>` or even just `Func<HttpContext, Task>`?

**Comment by DamianEdwards** [comment]
@dustinmoris yep agreed, would be nice to have that one too. Not sure about going all the way to just `Get`, `Post`, etc. methods. Of course, nothing stopping anybody from creating those extensions methods themselves 😄

**Comment by Eilon** [comment]
@kichalla can you work with folks on finalizing a design, and then implement?

**Comment by kichalla** [comment]
cc @rynowak

**Comment by rynowak** [comment]
@DamianEdwards - we already have a bunch of extensions with similar flavour on `IRouteBuilder`. Hopefully what's there is a good match for what you had in mind or else it's going to get confusing.

**Comment by Eilon** [comment]
Done?? 😄

**Comment by Kralizek** [comment]
Too late to the party?

How about adding support to DI in the lambda we pass to the extension method? Very similarly to what we already have when authoring a middleware

```
.UseRouter(router => router
    .MapGet("hello/{*name}", async (HttpRequest req, HttpResponse res, RouteData data, IGreeter greeter) => await myService.GreetAsync(data.Values["name"]))
)
```
