### ISSUE TITLE
[Feature request] SEO/Slug Regex Constraint Groups

### ISSUE THREAD

**Issue by funkynicco** [aspnet/Routing#369]
Hi. This is a feature request proposal for fetching regex group values from the regex inline binding constraint.

*Apologize in advance if this feature request belongs to Mvc repository. Routing appears to be the correct department.*

In SEO/Slug urls, you'll often have something like  
`/article/294-this-is-the-title`  
where the only relevant part for the code here is `294` which is the ID of the article.  
*SEO urls can also be formed as `/article/294/this-is-the-title` but this is not what the feature is about.*

Now, how do you normally get the relevant ID only from this URL, as the name/slug part is irrelevant for database querying?  
The old way that I used to do it, is by having some extra code in the action method that grabs the ID part from the URL, as shown below.

```c#
[Route(@"[controller]/{id:regex(^\d+-.+)}")]
public IActionResult Index(string id)
{
    var articleId = int.Parse(Regex.Match(id, @"^(\d+)").Groups[1].Value);
    // ... omitted code
}
``` 
Note that the id parameter is already regex constrained to `^\d+-.+` in the `Route` attribute.

This can be solved by using parameter attributes.  
Note that the following example is not based on in-depth knowledge about Mvc or Routing, I did the research and wrote this code last night over a couple of hours.  
As such, the implementation can be done more performant and cleaner, this is only a demo of the feature.

The demo implementation I came up with involves a `FromRegexRoute` attribute that is placed before the parameter. This only stores the *Group* variable for user in regex matching.  
Along with it, a `RegexRouteRewriteActionFilter` that in my example is globally applied through Mvc filters, but it can be used as an attribute as well.  
*Note that globally registering this filter is likely a performance issue whereby it scans all action parameters. A better solution such as IModelBinder could be implemented.*

### FromRegexRouteAttribute

```c#
/// <summary>
/// Marks a parameter of an action that it uses the name:regex() constraint and that it has a group to fetch value from.
/// </summary>
[AttributeUsage(AttributeTargets.Parameter)]
public class FromRegexRouteAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the regex group to fetch the value from.
    /// </summary>
    public int Group { get; set; }
}
```

### RegexRouteRewriteActionFilter
```c#
/// <summary>
/// Rewrites the value of action parameters that has the <see cref="FromRegexRouteAttribute"/> attribute.
/// </summary>
public class RegexRouteRewriteActionFilter : IActionFilter
{
    private readonly ILogger<RegexRouteRewriteActionFilter> _logger;

    public RegexRouteRewriteActionFilter(ILogger<RegexRouteRewriteActionFilter> logger)
    {
        _logger = logger;
    }

    public void OnActionExecuting(ActionExecutingContext context)
    {
        // Loop through each action parameter
        foreach (var parameter in context.ActionDescriptor.Parameters)
        {
            var controllerParameter = parameter as ControllerParameterDescriptor;
            if (controllerParameter != null)
            {
                // Attempt to find the [FromRegexRoute] attribute.
                var regexRouteAttribute = controllerParameter.ParameterInfo.GetCustomAttribute<FromRegexRouteAttribute>();
                if (regexRouteAttribute != null)
                {
                    // Find the constraint regex -- Has a potential flaw in returning match too early if the regex itself contains )}
                    var parameterRegexMatch = Regex.Match(
                        context.ActionDescriptor.AttributeRouteInfo.Template,
                        "{" + parameter.Name + @":regex\((.*?)\)}");
                    if (!parameterRegexMatch.Success)
                        throw new FormatException($"Parameter {parameter.Name} in {context.ActionDescriptor.DisplayName} has [FromRegexRoute] but no valid regex was found in the template.");

                    // Grab the current value of the parameter
                    var parameterValue = (string)context.RouteData.Values[parameter.Name];

                    // Attempt to grab the group provided by the [FromRegexRoute] attribute of the parameter value.
                    var parameterGroupValueMatch = Regex.Match(parameterValue, parameterRegexMatch.Groups[1].Value);
                    if (!parameterGroupValueMatch.Success)
                        throw new FormatException($"The provided value for parameter {parameter.Name} was not matched in the regex route: {parameterValue}");

                    // Replace the old value with the matched group value.
                    var oldValue = context.RouteData.Values[parameter.Name];
                    var newValue = parameterGroupValueMatch.Groups[regexRouteAttribute.Group].Value;

                    context.ActionArguments[parameter.Name] = Convert.ChangeType(newValue, parameter.ParameterType);
                    context.RouteData.Values[parameter.Name] = Convert.ChangeType(newValue, parameter.ParameterType);

                    // Trace this rewrite for debugging purposes
                    _logger.LogTrace(
                        "Rewrote parameter '{0}' in {1} - '{2}' => '{3}'",
                        parameter.Name,
                        context.ActionDescriptor.DisplayName,
                        oldValue,
                        newValue);
                }
            }
        }
    }

    public void OnActionExecuted(ActionExecutedContext context)
    {
    }
}
```

The MVC action method is now rewritten as following.

```c#
[Route(@"[controller]/{id:regex(^(\d+)-.+)}")]
public IActionResult Index([FromRegexRoute(Group = 1)] int id)
{
    // ... omitted code
}
```

Please note 2 important changes. The regex in the Route attribute now has a group for matching the initial number,  
and the id parameter itself is now `int`.  
`RegexRouteRewriteActionFilter` grabbed the id value from the SEO url and turned it into an integer.

## Closing notes

I know there are a couple of ways to solve this issue, but this is request is still about a feature that can be used for so much more than just grabbing the id of an SEO url.  
The code is written in a way to explain the feature, it is not a finished product for implementation.  
I originally attempted to use IModelBinder with no success - it appeared difficult to fetch the route template information and attributes, but more experienced in those sections may have a solution that solves this feature easily.

**Comment by rynowak** [comment]
Routes can already use 'complex' segments where a path segment (the part between the slashes) is split up according to some arbitrary logic. 

It seems like you could do something like this `/{controller}/{id}-{ignoreme}`

The `ignoreme` route value would capture all of the parts of the URL that don't want

**Comment by Eilon** [comment]
No plans to implement this feature because there are already pretty decent ways to implement this.
