### ISSUE TITLE
[Routing]Raw route values should be restored after template binder failing binding values when generating a url

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Routing#370]
_From @anobaka on December 6, 2016 7:20_

### Minimal repro steps
1. Create a sample .net core web application.
2. Modify the `app.UseMvc...` line to:
```
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "test",
        template: "{area?}/{controller=Home}/{action=Index}/{id?}"
    );
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
});
```
3. Add `TestController` and an `Index` action in it.
4. Add `var a = Url.Action("Index", "Test");` in `Index` Action of `HomeController`.
5. Run app and visit `/`.

### Expected result
local variable `a` should be `/Test`

### Actual result
the value of `a` is `/`

### Further technical details
I checked the source of `Routing` and found that the raw route values will not be restored after template binder failed binding values. So when the `default` router was tring to generate url, there was `action:Index` only left in route values, so it used the default controller `Home`.
ref:
[https://github.com/aspnet/Routing/blob/rel/1.1.0/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L238](https://github.com/aspnet/Routing/blob/rel/1.1.0/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L238)
[https://github.com/aspnet/Routing/blob/rel/1.1.0/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L279](https://github.com/aspnet/Routing/blob/rel/1.1.0/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L279)
I think the logic is that all routers should try to bind raw route values to generate url, but not the route values modified by previous router, so the raw route values should be restored after each router binding or routers should use the copy of the raw route values.

Thanks.

_Copied from original issue: aspnet/Home#1860_

**Comment by javiercn** [comment]
@rynowak

**Comment by rynowak** [comment]
@Eilon - we should investigate this, if there's a bug here this is a good 1.1.1 candidate.

**Comment by Eilon** [comment]
I'm able to reproduce this and it definitely looks wrong.

**Comment by kichalla** [comment]
Looking into it now...

**Comment by Eilon** [comment]
@kichalla - is this fix for 1.1.1? If so, it's fine to merge for 'dev', but we need the bug to remain open so we can track for 1.1.1...

**Comment by kichalla** [comment]
Yeah, it was for 1.1.1 and was merge to 'dev'. Sure, reopening it.

**Comment by Eilon** [comment]
Understood, thanks!

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
@kichalla does this just needs to be Closed/3-Done now? The change is already in the right branch?

**Comment by Eilon** [comment]
Oh wait nevermind we need to port the commit, so there's actual work here.

**Comment by kichalla** [comment]
The fix was already merged back (3rd Jan) into 'dev' if that is what you mean: https://github.com/aspnet/Routing/commits/dev

**Comment by Eilon** [comment]
Ah that's right, so we effectively just need to port it.

**Comment by pranavkm** [comment]
@Eilon, the change is in https://github.com/aspnet/Routing/tree/rel/1.1.1 and in the dev branch. Doesn't look like we need to do anything more.

**Comment by Eilon** [comment]
Oh weird... we had a 1.1.1 branch for that long? That's cool.

**Comment by Eilon** [comment]
@kichalla if you agree with the facts, it sounds like you can just close this!

**Comment by rynowak** [comment]
> if you agree with the facts

I'm interested to see if he does. He likes Pepsi

**Comment by kichalla** [comment]
:-)
