### ISSUE TITLE
Rename "Map" methods to HTTP verbs in RequestDelegateRouteBuilderExtensions

### ISSUE THREAD

**Issue by jchannon** [aspnet/Routing#378]
In this file we have `MapGet`, `MapDelete`, why not just make them `Get, Delete` etc?

**Comment by Eilon** [comment]
@jchannon they're there to align with the various other `MapXyz` APIs that we have elsewhere. Also, we generally follow the .NET Framework Design Guidelines that recommend having a proper verb stating what the method is doing. (Yes, get/delete/etc. are also verbs, but in this context they are nouns.) Without the verb `Map` it would look a little like the method call is *getting* something or *deleting* something (which, of course, they are not).

**Comment by jchannon** [comment]
They would be getting/deleting something.

**Comment by Eilon** [comment]
@jchannon yes, but the methods themselves aren't getting/deleting anything. Rather, they're creating a mapping so that later an HTTP request can get/delete something.

**Comment by jchannon** [comment]
What is this doing then? You have a GET for /contacts that returns a list of contacts. `r.Get` makes it clearer to me what is going on. The `Map` prefix is superfluous 

```
 .Configure(app =>
            {
                // define all API endpoints
                app.UseRouter(r =>
                {
                    var contactRepo = new InMemoryContactRepository();
 
                    r.MapGet("contacts", async (request, response, routeData) =>
                    {
                        var contacts = await contactRepo.GetAll();
                        await response.WriteJson(contacts);
                    });
                }
              }
```

**Comment by davidfowl** [comment]
It's not though. It's like calling it `r.OnGet`. You're registering a callback that will be invoked on a GET request. 

PS: I know you just want it to look like nancy 😛

**Comment by jchannon** [comment]
Exactly a callback `r.Verb(route, callback)`

PS : I know you do too, it would make the world a better place, you know it, I know it, we all know it 😄 


![you_know_it_boom](https://cloud.githubusercontent.com/assets/105126/22366174/340890e8-e473-11e6-9b37-1e69cf625011.gif)

**Comment by grumpydev** [comment]
If you're following the naming guidelines shouldn't it be MapGetAsync ? :trollface:

**Comment by davidfowl** [comment]
> If you're following the naming guidelines shouldn't it be MapGetAsync ? :trollface:

No because the method itself isn't async. The callback is.
