### ISSUE TITLE
MapHead

### ISSUE THREAD

**Issue by jchannon** [aspnet/Routing#397]
Is there a MapHead extension planned with MapGet etc? I have tried on a MapGet to set the ContentLength header and set the response.Body to empty but this makes the response return early before I can clear the body and just return the headers i.e on a HEAD you just want headers and ContentLength included

**Comment by jchannon** [comment]
I'm referring to these extensions https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/RequestDelegateRouteBuilderExtensions.cs

**Comment by rynowak** [comment]
We didn't have any immediate plans for this, but we'd take a PR or add it ourselves if there's enough demand.

For now you can add your own extension method or use `MapVerb` directly. See: https://github.com/aspnet/Routing/blob/20967cfa76913ee7acfe6d737877fa0af3c11e11/src/Microsoft.AspNetCore.Routing/RequestDelegateRouteBuilderExtensions.cs#L104

**Comment by jchannon** [comment]
I'm happy to do that. I'm just not sure how you go about clearing the
response body but setting the ContentLength header to what it should be.
Any ideas?

**Comment by rynowak** [comment]
It sounds like what you're trying to do is something different. These methods just control what URLs and HTTP methods go where. 

It's up to the app developer to implement the HEAD operation

**Comment by jchannon** [comment]
OK Thanks

**Comment by jchannon** [comment]
Where would be the best place to ask how to convert a GET to a HEAD?

**Comment by rynowak** [comment]
If you're just trying to prevent sending the body, write a middleware that replaces the `HttpContext.Response.Body` with a stream that no-ops, and then set `HttpContext.Response.ContentLength = 0`

**Comment by jchannon** [comment]
Not quite, I think I have it working how I want.

Essentially I've written a little lib over the top of the MapVerb extension
and so users can defined GET funcs and if they do a HEAD on the same route
I wanted it to execute the GET func set the content length header but clear
the body.  So I've essentially added and if statement to check if
req.Method == HEAD and if so set res.Body = new MemoryStream, let it handle
the func then get the body length, call res.Body.SetLength(0) and call
res.ContentLength = lengthBeforeCleared;  This seems to work ok. Sound ok
to you?



On 13 April 2017 at 16:40, Ryan Nowak <notifications@github.com> wrote:
>
> If you're just trying to prevent sending the body, write a middleware
that replaces the HttpContext.Response.Body with a stream that no-ops, and
then set HttpContext.Response.ContentLength = 0

**Comment by jchannon** [comment]
Not quite, I think I have it working how I want.

Essentially I've written a little lib over the top of the `MapVerb` extension
and so users can defined GET funcs and if they do a HEAD on the same route
I wanted it to execute the GET func set the content length header but clear
the body.  So I've essentially added and if statement to check if
req.Method == HEAD and if so set `res.Body = new MemoryStream()`, let it handle
the func then get the body length, call `res.Body.SetLength(0)` and call
`res.ContentLength = lengthBeforeCleared;`  This seems to work ok. Sound ok
to you?

**Comment by rynowak** [comment]
yep

**Comment by davidfowl** [comment]
@jchannon What server are you using?

**Comment by jchannon** [comment]
Kestrel

**Comment by jchannon** [comment]
I'm looking at Nancy with Kestrel and interestingly on a HEAD with Nancy it will set the Content-Length header but using CURL & Postman, Kestrel is not returning that header on a HEAD

**Comment by jchannon** [comment]
Have raised an issue for Nancy here https://github.com/NancyFx/Nancy/issues/2734

However I'm not entirely sure whether the Content-Length should be set when `Transfer-Encoding: chunked` is defined which I think Kestrel does by default ???

**Comment by jchannon** [comment]
Interestingly on a normal GET request with the MapGet extension `Transfer-Encoding: chunked` is returned yet in my HEAD implementation it isn't returned. Is that because I'm using a `MemoryStream` and the default `FrameResponseStream` sets the `Transfer-Encoding: chunked` by default?

**Comment by jchannon** [comment]
Interestingly when a GET is called headers returned are Date/Server/Transfer-Encoding but on a HEAD it's just Date/Server but CURL then stalls with `no chunk, no close, no size. Assume close to signal end`

**Comment by rynowak** [comment]
At this point I'd suggest opening an issue on https://github.com/aspnet/KestrelHttpServer - this seems worth looking into.
