### ISSUE TITLE
Investigate skipped TemplateParser tests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Routing#407]
There are two tests in TemplateParserTests that are skipped on all tests runs because they fail.

- Parse_ComplexSegment_OptionalParameterFollowingPeriod_LastSegment
- Parse_ComplexSegment_OptionalParametersSeperatedByPeriod_Invalid

**Comment by SteveSandersonMS** [comment]
Both of these were fixed in #408 and are no longer skipped.

**Comment by rynowak** [comment]
Cool beans!
