### ISSUE TITLE
Restrict route to namespace

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Routing#419]
https://stackoverflow.com/questions/34306891/restrict-route-to-controller-namespace-in-asp-net-core

Is this achievable yet within the supplied libraries? Is it a planned future feature?

**Comment by Eilon** [comment]
Closing because this looks like a dup of https://github.com/aspnet/Mvc/issues/6570.

**Comment by Mardoxx** [comment]
Does this not belong here instead?

**Comment by Eilon** [comment]
@Mardoxx - the selection of controllers/namespaces is an MVC concern. Routing doesn't know what it's routing to.
