### ISSUE TITLE
Consider providing a composite router

### ISSUE THREAD

**Issue by dazinator** [aspnet/Routing#420]
`IRouter` and `IFileProvider` seem to be very similar in nature - i.e they resolve some request / path to some end point / handler.
With `IFileProvider` there is a `CompositeFileProvider` so you can wrap an array of `sub` IFileProviders to incorporate files from different sources.
I have just had to implement a similar concept for `IRouter` i.e a Composite Router that wraps an array of IRouters and passes the request through to the `IRouter` that matches first. This is useful for a modular application, in which each module has its own `IRouter` and more can be added dynamically by adding / removing an `IRouter` from the composite.
 This has me wondering, perhaps others have use for this and whether it would be nice to provide a `CompositeRouter` in the framework similar to FileProvider.

**Comment by Eilon** [comment]
I believe that nested routing is already supported. In fact, if you look at IRouteCollection, you can see that it implements IRouter.

**Comment by dazinator** [comment]
Ah I see - thank you.
So I need not have implemented my own Composite `IRouter` - doh!
I do need to be able to tell which `IRouter` has handled the request. Looking at the `RouteCollection` class I think I can just look at `context.RouteData.Routers` to work that out. I am assuming if thats a collection, then the last router will be the one that is handling the request. I'll expeirment with that.
Cheers.

**Comment by rynowak** [comment]
That should do what you want, that's what we use inside of MVC when we need to find out things
