### ISSUE TITLE
If non area route is first and can theoretically match (but actually no controller/action), link generation will generate incorrect urls

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Routing#422]
A non area route should not match a route that has Area set in the RouteData

1. `UrlHelper.Action()`
2. Calls GetVirtualPath with `routeName: null` (usually the router on UrlHelper is a RouteCollection)
3. RouteCollection will when routeName == null do a loop over all routes and call GetVirtualPath on each of them until the first match.

However for [RouteCollection](https://github.com/aspnet/Routing/blob/032bcf43b2cefe641fc6ee9ef3ab0769024a182c/src/Microsoft.AspNetCore.Routing/RouteCollection.cs) `GetVirtualPath` goes through a completely different verification flow than `RouteAsync` as RouteAsync will keep looping until one of the routes actually found a reachable RequestDelegate and set it on the `context.Handler` prop.

So either link gen would have to actually check for existence of the controller and action, or it should start to take into account the Area. Currently link gen just results in completely different urls from what the router would actually be able to reach

**Comment by Eilon** [comment]
@kichalla can you take a look to see what's going on here? It's hard to tell from a glance if this is by design or not.

**Comment by rynowak** [comment]
https://github.com/aspnet/Announcements/issues/120

**Comment by NinoFloris** [comment]
Ok, we fixed it for now by having all of our routes attached to areas. What would be nice then is being able to specify a default area, which is why we had our default routes in the first place.

**Comment by rynowak** [comment]
If you can provide an example (with code) of what your routes look like we can try to help.

**Comment by NinoFloris** [comment]
```cs
 app.UseMvc(routes =>
            {   
                routes.MapAreaRoute(
                    name: "defaultRoute",
                    areaName: "Mvc",
                    template: "{controller=Home}/{action=Index}/{id?}",
                    defaults: new { area = "Mvc" });
                
                routes.MapAreaRoute(
                    name: "internalAreaRoute",
                    areaName: "Internal",
                    template: "internal/{controller=Home}/{action=Index}/{id?}",
                    defaults: new { area = "Internal" });
                
                routes.MapAreaRoute(
                    name: "customerAreaRoute",
                    areaName: "Customer",
                    template: "{customer}/{project}/{controller=Home}/{action=Index}/{id?}",
                    defaults: new { area = "Customer" });
            });
```

Specifically customer clashes with default as arealess default routes match customer/project/{optionalfragments} as well

We're basically trying to get github style routing working.
This means base paths like account/logout but also NinoFloris/MyProject
Internal is not really an issue as it has a literal prefix

**Comment by rynowak** [comment]
We have a route constraint that will enforce the the route value matches something real. You could apply that to controller and action: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/KnownRouteValueConstraint.cs

```
routes.MapAreaRoute(
                    name: "defaultRoute",
                    areaName: "Mvc",
                    template: "{controller=Home}/{action=Index}/{id?}",
                    defaults: new { area = "Mvc" },
                    constraints: new { controller = new KnownRouteValueConstraint(),  });
```

This will verify on URL matching and URL generation that your controller is an existing controller. Customize the code of this to your liking.. for instance it won't verify that it's a valid combination of area/controller/action, it will just check that the controller exists.

Alternatively you could use attribute routing. Attribute routing has the behavior you're describing (it only links to things that actually exist).

**Comment by NinoFloris** [comment]
Ahh nice that constraint will work just fine I suppose

**Comment by NinoFloris** [comment]
I'll try that, if it doesn't quite work I'll reopen 😄  thank you for your time and suggestions 👍
