### ISSUE TITLE
Scoped objects set in middleware are lost after Routing

### ISSUE THREAD

**Issue by andreasandreou** [aspnet/Routing#432]
Hi guys,

I have an object like below:

```
public class MyObject
{
    public string MyProp { get; set; }
}
```

and I register a scoped service for it like below:

`services.AddScoped<MyObject>();`

then I have a middleware that sets a value for this object. This middleware is added before AddMvc(). All middlewares before AddMvc() that take MyObject using DI can access the value I set in the middleware. Everything after AddMvc() including my controllers get an instance of MyObject with null value for MyProp.

Can you please explain if this is by design? And if it is by design how can I have an object initialized in a middleware and not lost after Routing kicks in. It is important that this object is reinitialized for each request so adding it as a Singleton is not an option.

Thank you in advance,

Andreas

**Comment by davidfowl** [comment]
This doesn't sound like it has anything to do with routing. How are you resolving the ScopedObject?

**Comment by andreasandreou** [comment]
using dependency injection, i.e.
`MyController(MyObject myObject){...}`

**Comment by davidfowl** [comment]
That sounds highly unlikely. Can you put your sample project on github? That'll make it easier to investigate

**Comment by andreasandreou** [comment]
My company policies do not allow that but it is easy to replicate

1. Create new project in VS using ASP.NET Core Web Application (.Net Core) template
2. Add a class in the project with the following definition:
```
    public class MyObject
    {
        public string MyProp { get; set; }
    }
```
3. Add a middleware cclass in the project with the following definition
```
    public class MyObjectSetterMiddleware
    {
        private readonly RequestDelegate _next;
        private MyObject _myObject;

        public MyObjectSetterMiddleware(
            RequestDelegate next,
            MyObject myObject)
        {
            _next = next;
            _myObject = myObject;
        }

        public async Task Invoke(HttpContext context)
        {
            _myObject.MyProp = Guid.NewGuid().ToString("N");
            await _next.Invoke(context);
        }
    }
```
4. add the following line in StartUp.cs before services.AddMvc() line
`services.AddScoped<MyObject>();`
5. add the following line in StartUp.cs before app.UseStaticFiles(); line
`app.UseMiddleware<MyObjectSetterMiddleware>();`
6. Create a constructor in HomeController.cs like below:
```
        public HomeController(MyObject myObject)
        {   }
```
7. Check myObject.MyProp in HomeController and you will see that is null although it was set in middleware.

Regards,

Andreas

**Comment by andreasandreou** [comment]
Injecting MyObject in Invoke method of middleware instead of in the constructor solved my issue
