### ISSUE TITLE
URL generation should be able to be keyed off of non-string elements

### ISSUE THREAD

**Issue by Eilon** [aspnet/Routing#436]
Today's routing system is based entirely off of string dictionaries. We should have a way to have other data types, such as `Type` (e.g. of an MVC controller) act as inputs into locating a route for URL generation.

**Comment by Eilon** [comment]
Moving to Backlog as there are no plans to implement this at this time.

cc @rynowak FYI because of Dispatcher, though this isn't directly related (but might be interesting)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2664
