### ISSUE TITLE
Port TemplateParser/RouteTemplate to the dispatcher project

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#466]
Move the implementations of the Template Parser and Template object model to the dispatcher project.

We may want to do some redesign of these things, but for now let's just move/rename them.

**Comment by rynowak** [comment]
The implemenation in routing should be updated to use the code in dispatcher as much as possible.

**Comment by jbagga** [comment]
@rynowak Is moving the `Routing.Dispatcher` namespace part of this work item? We use `Routing` classes like `RouteValueDictionary` and some internal routing stuff there. Should those be moved now?

**Comment by rynowak** [comment]
I would start by moving the `RouteTemplate` and ``TemplateParser` to the dispatcher project.  If these use RVD, update the to use `DispatcherValueCollection`
