### ISSUE TITLE
Support IgnoreRoute

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Routing#47]

**Comment by kscott5** [comment]
So, I've looked and could not find MapMvcAttributeRoutes or IgnoreRoutes as it relates to ASP.NET vNext. Is it implement? If not, how do I use the conventional base routing as it relates to Microsoft.AspNet.Mvc?

**Comment by yishaigalatzer** [comment]
@kscott5 IgnoreRoute was not yet implemented (as indicated by this issue being open), so you need to remove the `routes.IgnoreRoute` for now.

`MapMvcAttributesRoutes` is no longer necessary, and you can safely remove the line. Attribute routes just work by default.

**Comment by ChrisFelstead** [comment]
My issue has been moved and I've been ask to supply a case. In short, I can a wildcard route in order to allow for views without a controller (these are static pages but with the same design template). The issue is that I need to exclude common extensions (images, css, JavaScript, documents etc...) and cant without IgnoreRoutes.

**Comment by Eilon** [comment]
@ChrisFelstead one thing to note about ASP.NET Core MVC (the new MVC) is that if the incoming URL matches a route that is intended for MVC, but MVC can't find a matching controller/action, MVC ignores it, and the request will continue to the next middleware. Also, generally the Static Files middleware should be registered before the MVC middleware (that is, call `UseStaticFiles()` before `UseMvc()`).

I'm curious - did you try this and it didn't work? And if so, what exactly happened?

**Comment by ChrisFelstead** [comment]
I had this is my startup. I expected it to run the wildcard route if no appropriate route found but ignore static files like images, js, css and documents. It's applying to everything so I wanted to use ignore routes to exclude them extensions.

Basically, Im to achieve the ability to have views without a controller for static pages. But I need the ability to use the layout (hence why I dont make html pages)

===

app.UseStaticFiles();

app.UseMvc(routes =>
{
//routes.MapRoute(
// name: "RP",
// template: "RP/{controller=Home}/{action=Index}/{id?}",
// defaults: new { area = "RP" });

routes.MapRoute(
name: "default",
template: "{controller=Home}/{action=Index}/{id?}");

routes.MapRoute("Wildcard Routing",
"{*anything}",
new { controller = "Wildcard", action = "Get" },
new { anything = @"^(.*)?$" });

**Comment by Eilon** [comment]
Hmm that looks like it should work for this scenario:

1. If the incoming request matches a file that exists on disk, serve it (static file middleware should catch all these)
2. If the incoming request matches an existing MVC controller/action, run that
3. Send all other requests to `WildcardController.Get()`

But that's not what's happening?

**Comment by ChrisFelstead** [comment]
Nope. I thought it should too. All requests (including the js and css) are going to the controller. I'll do some more investing tomorrow and get back to you with specific cases and a sample project if you would like.

On 29 Feb 2016, at 17:09, Eilon Lipton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm that looks like it should work for this scenario:

  1.  If the incoming request matches a file that exists on disk, serve it (static file middleware should catch all these)
  2.  If the incoming request matches an existing MVC controller/action, run that
  3.  Send all other requests to WildcardController.Get()

But that's not what's happening?

-

**Comment by Eilon** [comment]
Is this on a machine with a case-sensitive file system (e.g. Linux), and the requests are coming in with the wrong casing?

**Comment by ChrisFelstead** [comment]
No. Its running on Windows. And Im using the default project template.

**Comment by rynowak** [comment]
You should be able to see some relevant information in the debug output window from logging if you're using VS and the default template.

**Comment by Eilon** [comment]
An the `webroot` property in `project.json` is pointing at the correct folder (usually `wwwroot`)?

Does the plain old regular default project template (without any modifications) serve static files correctly?

**Comment by ChrisFelstead** [comment]
Interesting. Got a colleague to open and run (as Im out of the office) the project and it works as expected. Getting 200 and 302s. The problems must be on my machine. Sorry to both you guys.

**Comment by Eilon** [comment]
@ChrisFelstead have your colleague join this program: http://blog.codinghorror.com/the-works-on-my-machine-certification-program/

You, on the other hand, cannot yet join this program :smile:

**Comment by dlebedynskyi** [comment]
@Eilon  we have same issues. dnx core rc1, Window 7 x64. Both on IIS and kestrel.  Static files if not found are passed to controller and are return an home/index page with text/plain.

I had to put attribute routing on home/index and remove all routing from ConfigureMvc. Something like 
```
[Route("~/")] // required to server root 
[Route("~/{controller}/{action}")] / any controller action etc
```

PS not at work machine now so code may be a bit wrong. but hope shows the idea. 
I with we had ignore route

**Comment by Eilon** [comment]
@dlebedynskyi can you log a new issue in this repo with precise repro steps? IgnoreRoute still shouldn't be needed for this scenario, so unless I'm missing something, this could just be a bug.

**Comment by dlebedynskyi** [comment]
@Eilon  great resolution. good job. too a lot of work I assume
