### ISSUE TITLE
InlineRouteParameterParser shouldn't exist

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#475]
`InlineRouteParameterParser` is a separate static class from the `TemplateParser` with its own public entry point that is responsible for parsing the contents of a parameter.

Example:
`{controller=Home}/{action=Index}/{id?}`

In this case it would be called once for `controller`, once for `action` and once for `id?`. 

There are some layering problems with this API overall
- It doesn't handle escaping
- It is called with the contents of the parameter, not the whole parameter
- It doesn't need to be public, it's a detail of the template parser
- It can't report errors, it always returns a 'parameter', even if it's in valid

---------

We should obsolete this method in `Microsoft.AspNetCore.Routing` and remove it in 3.0. For the dispatcher we should fix all of the above issues and not make this functionality public.

**Comment by rynowak** [comment]
We should do this after preview 1. It's not a critical issue

**Comment by rynowak** [comment]
I'm putting a few notes in the code related to this. Do a search for `#475` when you fix this.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2658
