### ISSUE TITLE
TemplateParser should be able to report multiple errors

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#476]
Currently the template parser code throws an argument exception with the first error it encounters in parsing a route template. 

We should have a custom exception type for this and expose rich information including the original template and **all** errors that were found. This will be more useful to extenders and will be needed by us when we do richer diagnostics functionality

**Comment by rynowak** [comment]
We should do this after preview 1 as it's not high priority, just polish

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2657
