### ISSUE TITLE
THIS ISSUE TRACKER IS CLOSED - use the Home repo issue tracker

### ISSUE THREAD

**Issue by Eilon** [aspnet/Routing#505]
Hello, this issue tracker is no longer used. Please log new issues here: https://github.com/aspnet/Home/issues

For information about this change, see https://github.com/aspnet/Announcements/issues/283

**Comment by mkArtakMSFT** [comment]
@Eilon, I'm closing this issue as we're reopening this repo for the Dispatcher work.

**Comment by Eilon** [comment]
Well the idea was to reduce how many issue trackers we use and to use aspnet/Home instead. But, if we want to use this issue tracker, I went ahead and deleted https://github.com/aspnet/Routing/commit/60ad99037eb16120feb9b177cea225d2427253a1 as well.
