### ISSUE TITLE
Shouldn't a routing constraint constructor use DI ?

### ISSUE THREAD

**Issue by ststeiger** [aspnet/Routing#512]
I have a routing constraint that limites entity names to db tables (mapped in EF-Core).

To do this, I have this:

```
[Microsoft.AspNetCore.Mvc.HttpGet("API/{entity:BlueMineTable}/Remove/{id:int}")]
public JsonpResult RemoveEntity(string entity, int? id)
{ ... }
```

```
 services.AddMvc();
            
            
            services.Configure<Microsoft.AspNetCore.Routing.RouteOptions>(options =>
                
                options.ConstraintMap.Add("BlueMineTable"
                    //, typeof(RouteConstraints.EntitiesRouteConstraint<BlueMine.Db.BlueMineContext>)
                    ,typeof(RouteConstraints.EntitiesRouteConstraint
                        <BlueMine.Db.BlueMineContext, 
                            BlueMine.Db.GenericEntityFramworkRepository<BlueMine.Db.BlueMineContext>,
                            BlueMine.Db.BlueMineRepository>)
                    )
            );
```

Now, the problem is, I can't get the EntityContext via DI in the constructor of the constraint. 
Therefore, I need to get it via httpContext.RequestServices, which I find a bit odd, as this doesn't need to be done on a per-request basis. 

So I have to always check on every Match if the hashtable, has been initialized, and if not, initialize it. 
This frankly is suboptimal, IMHO. 

[For reference:](https://github.com/ststeiger/BlueMine/blob/master/BlueMine/Code/RouteConstraints/EntitiesRouteConstraint.cs)

```

namespace BlueMine.RouteConstraints
{
    
    
    public class EntitiesRouteConstraint<TDbContext, TGenericRepository, TRepository> 
        : Microsoft.AspNetCore.Routing.IRouteConstraint 
        // we need TDbContext to define TGenericRepository
        where TDbContext: Microsoft.EntityFrameworkCore.DbContext
        // we need TGenericRepository to call our function
        where TGenericRepository: BlueMine.Db.GenericEntityFramworkRepository<TDbContext>
        where TRepository: TGenericRepository // we need TRepository for DI resolution 
        // TODO: Define interface for repository so EF can be dropped as dependency
    {
        
        private static object s_lock;
        private static System.Collections.Generic.HashSet<string> s_tables;
        
        
        static EntitiesRouteConstraint()
        {
            s_lock = new object();
        }
        
        
        public EntitiesRouteConstraint()
        { }
        
        
        // https://stackoverflow.com/questions/45667126/how-to-get-table-name-of-mapped-entity-in-entity-framework-core
        public void InitializeHashSet(System.IServiceProvider services)
        {
            lock (s_lock)
            {
                if (s_tables == null)
                {
                    TGenericRepository bmc = (TGenericRepository) 
                        services.GetService(typeof(TRepository));
                    
                    if (bmc == null)
                    {
                        // throw new System.NullReferenceException(nameof(bmc));
                        return;
                    } // End if (bmc == null)
                    
                    System.Collections.Generic.HashSet<string> hs = 
                        new System.Collections.Generic.HashSet<string>(
                        System.StringComparer.InvariantCultureIgnoreCase
                    );
                    
                    foreach (string table in bmc.ListTableNames())
                    {
                        hs.Add(table);
                    }
                    
                    s_tables = hs;
                } // End if (s_tables == null) 
                
            } // End lock (s_lock) 
            
        } // End Sub InitializeHashSet 
        
        
        bool Microsoft.AspNetCore.Routing.IRouteConstraint.Match(
              Microsoft.AspNetCore.Http.HttpContext httpContext
            , Microsoft.AspNetCore.Routing.IRouter route
            , string routeKey
            , Microsoft.AspNetCore.Routing.RouteValueDictionary values
            , Microsoft.AspNetCore.Routing.RouteDirection routeDirection)
        {
            if (routeDirection != Microsoft.AspNetCore.Routing.RouteDirection.IncomingRequest)
                return false;
            
            if (s_tables == null)
            {
                InitializeHashSet(httpContext.RequestServices);
            } // End if (s_tables == null)
            
            // object value = values[routeKey];
            
            object value;
            if (values.TryGetValue(routeKey, out value) && value != null)
            {
                return s_tables.Contains(value.ToString());
            }
            
            return false;
        } // End Function IRouteConstraint.Match
        
        
    } // End Function EntitiesRouteConstraint<T> 
    
    
}

```

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please look into this, thanks!

**Comment by pranavkm** [comment]
@rynowak is more familiar with this area, in particular if adding this feature would affect the dispatcher changes.

**Comment by rynowak** [comment]
DbContext is scoped, route constraints have application lifetime.

I would suggest resolving the DbContext per-request. When you constraint gets invoked you are provided the current `HttpContext`, which should allow you to resolve per-request services like the `DbContext`.

You can find an example of a contraint that resolves services here:  
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/KnownRouteValueConstraint.cs

**Comment by ststeiger** [comment]
Per request ? 
Why I would want to resolve the db-context on a per-request basis ? 
What for ? Multi-tenant application with single-tenant database based on the host-header ? 
Makes no sense IMHO, and introduces way to much latency, plus needlessly puts mindless load on the database. 

When I fetch the tables in the application, I do this only once, and then it's read-only during application-lifetime.  Why would I ever want a different db-context depending on the request ? 
(well, maybe in some obscure edge-cases - in which case I could still do it via httprequest.geet)

I certainly wouldn't want to create a new hash-table for every request - again latency. 
The case of the action descriptor is fundamentally different - as it isn't constant per request. 
But such logic makes little sense on the DB level.

The ifs and the static could be avoided if it had the db-context in the constructor, in my case. 
Or just pass an already-constructed singleton to ConstraintMap.

**Comment by ststeiger** [comment]
Factory would do the job, too. 
But that would make the first request slow. 
Is that really necessary ? 
Can't it just read/cache all it needs on application startup, and then use that information already at the first request ? So the first request will be fast, too ? 

Say, I update an application at 2 o'clock in the morning, when nobody is using it. 
At 5 o'clock the first users will start using it. 
Do the requests at 5 really need to be slow ? 
It had 3 hours to start up...  plenty of time for anything - ANYTHING.

Do I really want to write a script that issues HTTP requests to warm-up ? 
Do I really never forget to call that script after updating ? 
Do I want to have to call a script every time after updating ? 
Do I want to have to remember to call a script every time after updating ? 
Will I have to call N startup-scripts for N routes ? 
Sounds like baaaaaad to me.

**Comment by ststeiger** [comment]
Then it's fine ;)

**Comment by JamesNK** [comment]
I'm going to close this as done.

2.2 Preview 2 will be out next month and will support injected services on constraints. It would be great if you could try the preview and test whether it does what you want. If it doesn't we can reopen this issue.

**Comment by ststeiger** [comment]
Just tested. 
Works as expected - all good in my 10 minutes test, as far as I am concerned. 
How does it determine which constructor to use ? 
e.g.

```
// services.AddSingleton<RouteConstraints.GenericRepository>(new RouteConstraints.GenericRepository());

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace TestNetCore22.RouteConstraints
{


    public class GenericRepository  
    {

        public System.Collections.Generic.List<string> ListTableNames()
        {
            System.Collections.Generic.List<string> ls = 
                new System.Collections.Generic.List<string>();

            ls.Add("abc");
            ls.Add("def");

            return ls;
        }

    }


    public class EntitiesRouteConstraint
        : Microsoft.AspNetCore.Routing.IRouteConstraint
    {

        protected System.Collections.Generic.HashSet<string> m_tables;


        public EntitiesRouteConstraint()
        {
            System.Console.WriteLine("hello world");
        }


        public EntitiesRouteConstraint(GenericRepository repo)
        {
            System.Collections.Generic.HashSet<string> hs =
                       new System.Collections.Generic.HashSet<string>(
                       System.StringComparer.InvariantCultureIgnoreCase
                   );

            foreach (string table in repo.ListTableNames())
            {
                hs.Add(table);
            }

            this.m_tables = hs;
        }


        public EntitiesRouteConstraint(GenericRepository repo, string test)
        {
            System.Console.WriteLine(test);
        }


        bool Microsoft.AspNetCore.Routing.IRouteConstraint.Match(
              Microsoft.AspNetCore.Http.HttpContext httpContext
            , Microsoft.AspNetCore.Routing.IRouter route
            , string routeKey
            , Microsoft.AspNetCore.Routing.RouteValueDictionary values
            , Microsoft.AspNetCore.Routing.RouteDirection routeDirection)
        {
            if (routeDirection != Microsoft.AspNetCore.Routing.RouteDirection.IncomingRequest)
                return false;

            // object value = values[routeKey];
            object value;
            if (values.TryGetValue(routeKey, out value) && value != null)
            {
                return this.m_tables.Contains(value.ToString());
            }

            return false;
        } // End Function IRouteConstraint.Match


    } // End Function EntitiesRouteConstraint<T> 


}


```

**Comment by JamesNK** [comment]
https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Internal/ParameterPolicyActivator.cs#L103-L139

Matches on inline args and then most number of arguments to get from DI.

**Comment by rynowak** [comment]
Note that constraints have an **UNBOUNDED** lifetime. So if you try to access things like transient disposable services or a scoped service, expect some explosions.

**Comment by ststeiger** [comment]
Nice warning/catch - but that much should be obvious. 
But then again, who knows what all those services really do.

**Comment by rynowak** [comment]
Lots of folks expect that everything works everywhere 😁 I do my best now to make it clear what's supported, because if it accidentally works, then someone will use it.
