### ISSUE TITLE
MVC integration - endpoint matching

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#527]
- [x] Update abstractions
- [x] Invoke MVC action via conventional route
- [x] Invoke MVC action via attribute route

**Comment by JamesNK** [comment]
@rynowak How do you imagine conventional routing will work?

Off the top of my head it would be a helper method inside MVC, called at startup like `MapRoute`/`MapAreaRoute`, that a dispatcher data source then uses to resolve the matched template's route values to an action using the equivilent of `ActionSelector.SelectCandidates`, and then filter to a final result using `SelectBestCandidate`.

Warm/cold? Worth discussing in a call?

**Comment by rynowak** [comment]
Yes, that sounds about right. You might be able to reuse a lot of that code. Feel free to setup a call if there's more you want to discuss or confirm, but that's what I had in mind.

**Comment by JamesNK** [comment]
It's almost like what I know what I'm doing 🍰

**Comment by JamesNK** [comment]
Finished with https://github.com/aspnet/Mvc/pull/7928

Will open individual issues for additional fixes/features/work
