### ISSUE TITLE
Dispatching URL generation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#531]
# Overview
Dispatcher is a system which has deep knowledge of a set of endpoints and routes that make up an application. We need to provide a URL generation system that reflects the richness of this data but can be used by existing customers of Routing URL generation (MVC).

## Risks/Challenges
- We want existing users to migrate to Dispatcher work and since this is a point release, we do not want to break existing applications.
- Currently conventional routing and attribute routing are inconsistent when generating URLs.

## Requirements
Support generating URLs via a global singleton service without a request context.
Support generating URLs using current request context and ambient values (MVC).

----------------

Improve diagnostics when URL generation fails.(https://github.com/aspnet/Routing/issues/553)
- log when no endpoint was found.
- log when we have an endpoint but parameters and constraints are not satisfied.
- Maybe throw an exception when link generation fails as an option?

---------------------

URL generation should be 2-phase. (https://github.com/aspnet/Routing/issues/554)
 - Phase 1: Bind an address to a set of endpoints
 - Phase 2: Expand a template associated with one of those endpoints

**Questions:**
- Generate a bound delegate from a URL generator?
```
 - get uri template
 -  and use the template 1000 times
```
- https://tools.ietf.org/html/rfc6570

-----------------

Address finders (phase 1) should be extensible.
- Find endpoint(s) by name (string) - we need to ship
Implement a finder that is compatible with MVC.

--------------------------------------
phase 2:
- Route templates and URL link generation should support current primitives
- Discard ambient values (https://github.com/aspnet/Routing/issues/544)
- We need something like (RouteConstraints https://github.com/aspnet/Routing/issues/545)
--------------------------------------

Provide options to generate urls both at call site and globally. Like lower case urls, full qualified urls and trailing slashes
(https://github.com/aspnet/Routing/issues/547)

--------------------

2. Integration with MVC ( https://github.com/aspnet/Routing/issues/530)
    Works with both conventional and attribute routing
    Can generate links based on 'route name'
    Can generate links just based on route values.
    Attribute routing's link generation should match what conventional routing is doing

**Comment by kichalla** [comment]
Usage of ambient values in link generation has surprised users for a while now. At this point I think we could probably provide options globally or at call site to disable using ambient values.
Related issue: https://github.com/aspnet/Mvc/issues/7857
