### ISSUE TITLE
MVC IActionConstraint like functionality

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#534]
Current routing supports selecting the correct action via `IActionSelector` and `IActionConstraint`. Implement similar (or same) ability in dispatching. Design required.

**Comment by JamesNK** [comment]
@rynowak What on your thoughts on where `IActionConstraint` (`IEndpointConstraint`?) like functionality would live?

Will it be embedded inside the `Matcher` and the matcher is responsible for returning a final endpoint?

Alternatively would the matcher return a list of possible endpoints to something like `IEndpointSelector` and it would then select the best match using configured constraints?

**Comment by rynowak** [comment]
I think these are implementation details, so we have the flexibility to do whatever works best for us. If that's inside the matcher, then sure. Remember, it's a explicitly a non-goal to make part of the **dispatcher system** replaceable - so if we do factor it into two concerns then it should be internal 😆 

What I mean by this is that we want users to do things like implement a versioning policy, or implement something like https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/OverloadActionConstraint.cs


Beyond this known and well-defined scenario we're optimizing for perf, scalability, future maintainability, quality of diagnostics, etc over extensibility in this area. Providing flexibility that doesn't align with our core scenarios is a very low priority.

----

One detail that we didn't get right in `IActionConstraint` is that it's a bunch of separate policies that *vote* on whether their action is a match. It's complicated to reason about. I think it would be much much simpler to have a list of ordered policies that act on all actions at a time. Think of it as middleware for action selection.

----

The one non-straightforward thing that I feel obliged to point out is that the result of processing the URL will be (logically) a list of lists of candidates. The route tree has 'groups' of candidates where each 'group' has the same order and precedence. However we want to give any policy (like versioning) the ability to select from **all** groups, or at least to see candidates from all groups. 

I imagine that we could start with a list of lists, and then refine this into something more performant and nicer to code against once we've seen the complete picture. The set of candiates is largely static, so we can do lots of work to optimize the allocs.

---

Things like how the API design impacts allocations are definitely good to consider at this point. It's likely going to lead to us passing in some kind of mutable context.

Imagine for scoping that you'd have 1-8 endpoint candidates and 1-3 selection policies.

---

Another major decision point is whether the HTTP method feature will follow the same design as user-extensibility, will it implement some extensibility API or be totally built in? It's up to us 👍

**Comment by JamesNK** [comment]
Thanks for the detail! I started going down the path of having `IActionSelector` and it felt a little wrong. I'll roll that back and place constaining endpoints inside the matcher.

I'd like to pick your brain a bit more on the design but what I'm going to do short term is copy `IActionConstraint` across largely unchanged, get the same unit tests from MVC setup and running, and then we refactor that with a base of existing unit tests to let us know when we have broken something or lost some functionality.

**Comment by rynowak** [comment]
Sounds great!
