### ISSUE TITLE
Support for HTTP method filtering/disambiguation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#535]
Current routing does not support HTTP method. Close this gap in dispatching.

**Comment by JamesNK** [comment]
How baked into dispatching and endpoints do we want HTTP method matching?

Current routing doesn't care and relies on `IActionSelector`. Do we want to continue to have the filter on HTTP happen in a later selector method (still inside routing) or have it filtered along with the template.

Will there be performance benefits by not having to rely on a selector method to filter a list of candidates down?

**Comment by rynowak** [comment]
These sound like great questions to answer 😆 

>  Do we want to continue to have the filter on HTTP happen in a later selector method (still inside routing) or have it filtered along with the template.

I think we have the freedom to bake it in. I think if we keep it separate (inside MVC) then we'll need to solve the problem again and again.

**Comment by JamesNK** [comment]
I didn't mean leaving it to MVC, I meant whether the filtering to happen as part of the matcher or have a post matcher filtering. See https://github.com/aspnet/Routing/issues/534

**Comment by rynowak** [comment]
@JamesNK - done?
