### ISSUE TITLE
Public API review

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#538]
Review public API prior to RC.

**Comment by rynowak** [comment]
Can't review the public API if you want have one...

**Comment by JamesNK** [comment]
Pardon? By review I mean just going through all the new public types, e.g. IEndpointFeature, Endpoint, etc, and make sure we are happy with the names, namespaces, etc.

**Comment by rynowak** [comment]
It was a joke, I suppose we'll have to review those too

**Comment by JamesNK** [comment]
Prior to preview1 I'll review the public API myself.
Prior to RC I'll organize a meeting to review everything together.

**Comment by rynowak** [comment]
Let's also discuss whether `IEndpointSelectorPolicy` should be async.

**Comment by JamesNK** [comment]
Reviewed API prior to preview1 - https://github.com/aspnet/Routing/issues/676

Will have another API review in preview2 milestone.

**Comment by JamesNK** [comment]
Do we need another review session for 2.2?

**Comment by rynowak** [comment]
I don't think so. The only we didn't get through was the https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/INodeBuilderPolicy.cs and it's pretty esoteric.
