### ISSUE TITLE
Routing IRouteConstraint like functionality

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#545]
Routes today support `IRouteConstraint` (note that this is different from MVC's `IActionConstraint`) for ensuring checking that a route parameter is value for that constraint, e.g. the `id` parameter on a route is an integer.

**Comment by kichalla** [comment]
This needs to be addressed sooner than I imagined, so raising priority. cc @rynowak

**Comment by rynowak** [comment]
@kichalla done?

**Comment by kichalla** [comment]
> @kichalla done?

I kept this PR open to react to Routing's constraint functionality. I had a PR out for it but closed it as your PR addresses this already https://github.com/aspnet/Mvc/pull/8120
