### ISSUE TITLE
Micro-benchmark link generation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#572]
- [x] Micro-benchmark link generation
- [x] Micro-benchmark comparison between old UrlHelper and dispatching UrlHelper

**Comment by JamesNK** [comment]
@kichalla Is this complete with https://github.com/aspnet/Routing/commit/0986f74264d0e17f82b4548ed63c38f12969e9c9?

**Comment by rynowak** [comment]
I'm closing this, I think what we have is good enough to say that we've done all planned work.
