### ISSUE TITLE
Dispatcher MVC integration - Matching Razor pages support

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#579]
Controllers + actions are successfully matched via attribute and conventional routing. Razor pages still needs to be done.

See https://github.com/aspnet/Mvc/pull/7958 for examples of failing functional tests that use Razor pages.

- [ ] - Support Razor pages with dispatching
- [ ] - Add functional tests to MVC's RoutingWebsite

**Comment by JamesNK** [comment]
Can MVC pages be accessed using conventional routing?

**Comment by rynowak** [comment]
No

**Comment by JamesNK** [comment]
Razor Pages were support, failures were from a different issues that was fixed with https://github.com/aspnet/Mvc/pull/8047
