### ISSUE TITLE
Move fundamental types to HttpAbstractions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#607]
- RouteValueDictionary
- IEndpointFeature
- Endpoint
- Metadata collection

**Comment by rynowak** [comment]
Prerequisite of middleware work.

**Comment by rynowak** [comment]
Moving this to 3.0 with the change to scope.

**Comment by JamesNK** [comment]
Are you sure this should be 3.0? We will need to make the types public in routing and if we wait until 3.0 then we'll have to obsolete the 2.2 versions.

**Comment by rynowak** [comment]
Typeforwards mang

**Comment by JamesNK** [comment]
These types are already in abstractions.

**Comment by rynowak** [comment]
HttpAbstractions

**Comment by rynowak** [comment]
https://github.com/aspnet/HttpAbstractions/tree/master/src/Microsoft.AspNetCore.Http.Abstractions

**Comment by JamesNK** [comment]
Does the `Microsoft.AspNetCore.Routing` namespace stay the same after the move?

**Comment by rynowak** [comment]
yes

**Comment by JamesNK** [comment]
I put IEndpointFeature in a Microsoft.AspNetCore.Routing.Features namespace. That seems to be the standard for features.
