### ISSUE TITLE
Polish startup experience for Routing vNext

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#608]
We need to do here:
- [x] Update names for middleware and related concepts (`UseGlobalRouting`, `UseEndpoint`)
- [x] Update experience for MVC - "how can MVC users get Routing vNext without making code changes"
- [ ] Template updates (if necessary)

**Comment by rynowak** [comment]
What's the template update? just the compat switch?

**Comment by JamesNK** [comment]
Yeah. Will the 2.2 switch will be done as part of the regular release process and we don't need to worry about?

**Comment by rynowak** [comment]
@JamesNK close? Is this still tracking anything?
