### ISSUE TITLE
Back-compat support for IRoutingFeature on IEndpointFeature

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#625]
`RouteDataRequestCultureProvider` is unsurprisingly tied to routing. Do we want to create a version for dispatching?

**Comment by rynowak** [comment]
I think what we might want to do instead is to implement `IRoutingFeature` on the dispatcher feature (lazily). There's a **LOT** of code out there that uses `IRoutingFeature`, or `RouteData`, etc. We can do a pretty reasonable job implementing the route value part of this.

We might also need to do something to support data tokens

**Comment by JamesNK** [comment]
Sounds reasonable

**Comment by JamesNK** [comment]
`MiddlewareFilter_LocalizationMiddlewareRegistration_UsesRouteDataToFindCulture` is passing in MVC
