### ISSUE TITLE
MVC Functional Tests: HttpMethodEndpointConstraint restricts OPTIONS request

### ISSUE THREAD

**Issue by kichalla** [aspnet/Routing#631]
Following tests fail because OPTIONS request is rejected by the `HttpMethodEndpointConstraint`

![image](https://user-images.githubusercontent.com/6559784/42879863-004612d2-8a47-11e8-9cb0-32880b28535f.png)

cc @JamesNK

**Comment by rynowak** [comment]
See: https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Cors/Internal/CorsHttpMethodActionConstraint.cs

Action constraints have to be aware of CORS for something like this to work.

**Comment by JamesNK** [comment]
Fixed https://github.com/aspnet/Mvc/pull/8158
