### ISSUE TITLE
Flatten the LinkGenerationDecisionTree to show as debugger display string

### ISSUE THREAD

**Issue by kichalla** [aspnet/Routing#636]
Similar in the lines of https://github.com/aspnet/Routing/issues/633, it would be useful to flatten the `LinkGenerationDecisionTree` for easy diagnosis.

**Comment by rynowak** [comment]
If you want to do this kind of thing feel free. It's going to have a lot of impact if you do it now while we're still doing work in this area. If we wait it won't be worth doing 😆
