### ISSUE TITLE
API review mega-issue

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#676]
### Routing
- [x] Remove EndpointRoutingApplicationBuilderExtensions
- [x] Make middleware pub internal
- [x] seal CompositeEndpointDataSource
- [x] seal DefaultEndpointDataSource
- [x] review whether EndpointFeature.Invoker should be Func<RequestDelegate, RequestDelegate> or RequestDelegate
- [x] review whether EndpointOptions should be pub internal or internal?
- [x] make RoutePatternMatcher internal
- [x] move Microsoft.AspNetCore.Routing.EndpointFinders types to Microsoft.AspNetCore.Routing
- [x] rename RouteValuesBasedEndpointFinderContext to RouteValuesAddress
- [x] rename Microsoft.AspNetCore.Routing.Matchers to Microsoft.AspNetCore.Routing.Matching
- [x] remove CandidateState public ctors
- [x] remove MatcherEndpoint.RequiredValues, move to metadata
- [x] revisit MatchProcessor design in P2
- [x] revisit MatchProcessor vs MatchProcessorBase
- [x] move Microsoft.AspNetCore.Routing.Metadata to Microsoft.AspNetCore.Routing
- [x] make RoutePatternParameterPart sealed
- [x] remove InboundRouteEntry.Tag

### Routing Abstractions
- [x] seal EndpointMetadataCollection
- [x] add EndpointMetadataCollection params ctor
- [x] consider perf for `GetOrderedMetadata<T>()`
- [x] move IEndpointFinder to routing
- [x] move INameMetadata to routing
- [x] move IRouteNameMetadata to routing
- [x] move ISuppressLinkGenerationMetadata

### MVC Core
- [x] remove UseMvcWithEndpoint
- [x] see if MvcEndpointInfo can be internal

**Comment by mkArtakMSFT** [comment]
@JamesNK, thanks for filing this.
I'm moving this to preview2 for the sake of assigning a milestone. I believe the desire here is to have this meeting right after preview1 is shippeed. I'll leave it up to you to drive.

**Comment by JamesNK** [comment]
We had the API review meeting yesterday. We're aiming to have these changes done this week for preview1.

Will have another in preview2.

**Comment by rynowak** [comment]
I think that `IRouteNameMetadata` needs to be renamed, and also to include required values from the endpoint - then we should have an implementation.

**Comment by JamesNK** [comment]
DONE 🎉
