### ISSUE TITLE
XML docs for 2.2.0 additions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#686]
# List of new things to add docs:

#### Routing
- [x] Endpoint
- [x] IEndpointFeature
- [x] EndpointFeature
- [x] EndpointMetadataCollection
- [x] LinkGenerator
- [x] LinkGeneratorContext
- [x] RouteData.RouteData(RouteValueDictionary values)
#### MVC
- [x] MvcOptions.EnableEndpointRouting

#### Routing
- [x] Everything new in `.Patterns`
- [x] EndpointDataSource
- [x] CompositeEndpointDataSource
- [x] DefaultEndpointDataSource
- [x] `IEndpointFinder<TAddress>`
- [x] INameMetadata
- [x] IRouteNameMetadata
- [x] IRequiredValuesMetadata
- [x] ISuppressLinkGenerationMetadata
- [x] RouteOptions.LowercaseQueryStrings
- [x] RouteValuesAddress
- [x] CandidateSet
- [x] CandidateState
- [x] EndpointSelector
- [x] MatcherEndpoint
- [x] HttpMethodMetadata
- [x] IHttpMethodMetadata
- [x] MatcherPolicy
- [x] IEndpointComparerPolicy
- [x] IEndpointSelectorPolicy
- [x] HttpMethodMatcherPolicy
- [x] `EndpointMetadataComparer<TMetadata>`

## P2 (cut)
- [ ] LinkGenerationDecisionTree.GetMatches
- [ ] INodeBuilderPolicy
- [ ] PolicyJumpTable
- [ ] PolicyJumpTableEdge
- [ ] PolicyNodeEdge
- [ ] InlineConstraint.InlineConstraint(RoutePatternConstraintReference other)
- [ ] RouteTemplate.RouteTemplate(RoutePattern other)
- [ ] RouteTemplate.ToRoutePattern
- [ ] TemplatePart.TemplatePart(RoutePatternPart other)
- [ ] TemplatePart.ToRoutePatternPart
- [ ] TemplateSegment.TemplateSegment(RoutePatternPathSegment other)
- [ ] TemplateSegment.ToRoutePatternPathSegment
- [ ] OutboundRouteEntry.Data

## SUPER CUTSVILLE (not long for this world)
- [ ] MatchProcessor
- [ ] MatchProcessorBase

**Comment by rynowak** [comment]
@JamesNK - if you have the list from our API review could you help fill this out?

**Comment by rynowak** [comment]
Some additions here: https://github.com/aspnet/Routing/pull/687

**Comment by JamesNK** [comment]
I have thrown a whole bunch in. Some may have already been documented.

**Comment by rynowak** [comment]
I'm working through a set of docs improvements for the candateset matcherpolicy and related types.

**Comment by JamesNK** [comment]
All main APIs documented. Will document remaining items if there is a demand for it.
