### ISSUE TITLE
List mapped routes

### ISSUE THREAD

**Issue by Aveline67** [aspnet/Routing#700]
It would be very helpfull to list in log all mapped route.

I am actually figuring out why every possible URL returns 404. I do perfectly understand it matches no routes, no actions, but what are actually registered routes in my projet ? Sometimes it like lousing a day for nothing. So much painfull erverything works, than 404 every where, I dont now what is registered or not

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Aveline67.
This is something we have already implemented in the Endpoint Routing, which we hope to ship in the upcoming release (2.2). Here is the issue tracking that work: https://github.com/aspnet/Routing/issues/633
Closing this one as a dupe.
