### ISSUE TITLE
Rename MatcherEndPoint to RouteEndPoint

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Routing#711]
Because it's a route 😄

**Comment by JamesNK** [comment]
`Microsoft.AspNetCore.Routing.RouteEndpoint` 👍

**Comment by davidfowl** [comment]
ENDPoint

**Comment by rynowak** [comment]
`Microsoft.AspNetCore.Routing.XxXRo|_|teEnDp01ntXxX

**Comment by JamesNK** [comment]
Done https://github.com/aspnet/Routing/pull/712
