### ISSUE TITLE
DfaMatcher performance 2.2.0-preview2

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#727]
# Plaintext
- [x] Investigate `string.CompareOrdinal` - can we do better when we know it's ASCII?

- [x] Can we make `HttpContext.Request.Path.Value` faster? 
![image](https://user-images.githubusercontent.com/1430011/44236613-7bc25380-a162-11e8-9bd9-d4357a3301ee.png)

- [x] Why is `new CandidateSet` so expensive? 
![image](https://user-images.githubusercontent.com/1430011/44236711-c6dc6680-a162-11e8-9d7c-f43616cf7e83.png)

- [x] Why is `flags & ...` so expensive?
![image](https://user-images.githubusercontent.com/1430011/44236734-da87cd00-a162-11e8-9362-8e4362d94ee8.png)

- [x] Initializing the `IEndpointFeature` is too expensive
![image](https://user-images.githubusercontent.com/1430011/44236837-3fdbbe00-a163-11e8-8bcb-2c338ac6c8d8.png)

- [x] Should we redesign `CandidateSet` as a wrapper over an array, or a ref-struct

# Azure

- [x] Improve `DictionaryJumpTable`

![image](https://user-images.githubusercontent.com/1430011/44237934-5d128b80-a167-11e8-9724-b2220b3121ab.png)

**Comment by Yves57** [comment]
@rynowak I hope that replacing the `string` by a `StringSegment` in the `DictionaryJumpTable._dictionary` could allow to remove the substring creation in `DictionaryJumpTable.GetDestination`. Are you already working on optimizations of `DictionaryJumpTable`? Otherwise I propose you to explore this idea.

**Comment by rynowak** [comment]
Closing this. I've investigated or fixed all of these things as much as I think is reasonable.
