### ISSUE TITLE
EndPointDispatcher LinkGeneration produces empty strings when a route cannot be found

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Routing#728]
See https://github.com/aspnet/Mvc/pull/8275/files#r210713067

**Comment by dougbu** [comment]
Why is this "100%" intended? The 404s mean something while silently going back to the original URL is a major problem in many cases.

**Comment by rynowak** [comment]
New routing is like attribute routing, which doesn't like to actions that don't exist.  We could do additional work to try and simulate what old routing does, and we're planning to do that based on user feedback.  

Neither old nor new behavior does a good job alerting you that you have a problem, do you have suggestions about that?

**Comment by dougbu** [comment]
> do you have suggestions about that?

My suggestion is _not_ to hide developer typos and the like in an apparently-successful round trip. The previous behaviour at least resulted in an obvious failure albeit only when the broken link was used.

Moving the failure earlier e.g. resulting in a useful error page would be great. Even `throw`ing from the tag or HTML helpers may be fine now that the developer exception page displays the offending line in the `.cshtml` file. (Would be better if that part of the stack trace were open by default.)

**Comment by mkArtakMSFT** [comment]
Closing this bug per @rynowak's point. Let's ship as is and react to feedback later.
