### ISSUE TITLE
EndPointRouting LinkGeneration does not preserve passed in case of route values

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Routing#731]
With 2.1 link generation, `<a asp-action="test">`, the generated link preserves the specified case e.g. `<a href="Home/test">`

With 2.2 link generation, the generated link is `<a href="Home/Test">`

**Comment by rynowak** [comment]
This is an intended change in behaviour. We're doing a feature in preview3 that will let application developers canonicalize the the casing and formatting of things like action and controller names. This is a much better way of satisfying this user desired than putting canonicalization at the every call site to link generation.
