### ISSUE TITLE
Check MVC can read data tokens

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#740]
re: https://github.com/aspnet/Mvc/pull/8303#discussion_r211831974

**Comment by rynowak** [comment]
🐑-ishly... yeah It's possible we don't have any functional tests for this in MVC. Which is a little embarassing.

**Comment by rynowak** [comment]
The test you linked uses a filter to modify the data tokens inside a controller, https://github.com/aspnet/Mvc/blob/release/2.2/test/WebSites/RoutingWebSite/Controllers/RouteDataController.cs#L29 - however it doesn't have any data tokens defined in the route.

It would be enough to add an additional data token in the route definition (startup.cs) and verify that's passed through unmodified from routing.

**Comment by JamesNK** [comment]
Yup, test fails in endpoints. Will investigate a fix.

**Comment by JamesNK** [comment]
@rynowak I've got a question for you about require values, default values and route values.

So anything that is a required value is added to default values, including null.
e.g.
requiredValues: area=null
defaultValues: area=null

https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcEndpointDataSource.cs#L491-L511

Now anything in defaultValues is included in RouteValues when an endpoint is matched, including null. This is different from the previous routing behavour which is to not include null RouteValues.

Question is: what is the correct fix here?
1. Make it so null requiredValues aren't set to defaultValues (and so don't end up in RouteValues)
2. Make it so the endpoint matcher doesn't have null RouteValues
3. Change existing behavour and allow null RouteValues
