### ISSUE TITLE
System.InvalidOperationException: 'Cannot use 'UrlSlugRoute' with Global Routing.'

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Routing#743]
Hello,

I am trying to migrate a solution from ASP.NET Core 2.1.1 to ASP.NET Core 2.2 Preview 1.
After setting CompatibilityVersion to (CompatibilityVersion.Version_2_2), I got the following isssue:
![image](https://user-images.githubusercontent.com/1798510/44491629-2efae300-a662-11e8-9882-d2e486ef406b.png)

**Comment by rynowak** [comment]
Would it be possible for you to tell us more about `UrlSlugRoute`? If this is something you wrote could you show the code? I'm curious to see if this is something we can make work with the new system

**Comment by MaherJendoubi** [comment]
Sure @rynowak : 
https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Extensions/UrlSlugRoute.cs

**Comment by JamesNK** [comment]
They are the same thing. Global routing was renamed to endpoint routing. The text in your exception message was missed during the rename.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
