### ISSUE TITLE
Enable easier access to the matched route pattern

### ISSUE THREAD

**Issue by tillig** [aspnet/Routing#776]
The short version: In trying to gather statistics for an API, having access to the _route pattern_ that was matched is important but is very hard to access. Endpoint routing makes it easier, but it'd be nice to have even easier access.

**It very well could be I'm missing something obvious, and if so, please let me know.**

Longer: An API (or web site) may have a route like `/api/products/{id}`. When gathering statistics about usage, performance, etc. for the API, having access to this route pattern rather than a full route (like `/api/products/123`) is required to normalize the set of gathered statistics into logical buckets. While at first one might consider the controller/action combination a good fallback, as APIs get refactored, the actual contract that executes is based on the route, not a class/method name, and changing the class/method that handles a given route breaks statistics history.

Effectively, what you want stats on is a combination of route and HTTP verb - `GET /api/products/{id}` or `POST /api/products/{id}` for example.

In ASP.NET Core 2.1 you can grab the `DiagnosticListener` and add a subscriber that handles the `OnBeforeAction` event, which then provides the `ActionDescriptor` being executed, which then may or may not have an `AttibuteRouteInfo` property set from which you can get the route template. That diagnostic listener might look like:

```csharp
public class TemplateDiagnosticListener
{
    [DiagnosticName("Microsoft.AspNetCore.Mvc.BeforeAction")]
    public virtual void OnBeforeAction(HttpContext httpContext, RouteData routeData, ActionDescriptor actionDescriptor)
    {
        if (actionDescriptor.AttributeRouteInfo == null)
        {
            return;
        }

        var normalizedTemplate = actionDescriptor.AttributeRouteInfo
                                                 .Template
                                                 .ToLowerInvariant()
                                                 .TrimStart('/')
                                                 .TrimEnd('/');
        // Then you can do something with the template.
    }
}
```

...and you can subscribe with...

```csharp
var diagnosticListener = app.ApplicationServices.GetRequiredService<DiagnosticListener>();
var myListener = new TemplateDiagnosticListener();
var subscriber = diagnosticListener.SubscribeWithAdapter(myListener);
var appLifetime = app.ApplicationServices.GetRequiredService<IApplicationLifetime>();
appLifetime.ApplicationStopped.Register(() => subscriber.Dispose());
```

That's pretty painful and I haven't found a better mechanism in 2.1 to get that.

In the 2.2 preview using the endpoint routing it appears you can write some middleware akin to this:

```csharp
public class EndpointLoggingMiddleware
{
    private readonly ILogger<EndpointLoggingMiddleware> _logger;

    private readonly RequestDelegate _next;

    public EndpointLoggingMiddleware(RequestDelegate next, ILogger<EndpointLoggingMiddleware> logger)
    {
        this._next = next;
        this._logger = logger;
    }

    public async Task Invoke(HttpContext httpContext)
    {
        await this._next(httpContext);
        var endpointFeature = httpContext.Features.Get<IEndpointFeature>();
        this._logger.LogInformation("Request matched: {endpoint}", endpointFeature.Endpoint.DisplayName);
    }
}
```

As long as that runs before the MVC middleware, that can grab the endpoint feature and get the info you need. However, the `endpointFeature.Endpoint` still doesn't have easy access to the matched template. Right now you can try to cast to `Microsoft.AspNetCore.Routing.Matching.MatcherEndpoint` and use the `RoutePattern` property on that, but that still seems like it's a lot of magic and challenge to get something that should be pretty readily available.

If it's not something handled by MVC/routing, I can see where you may have to fall back to just using the path... but maybe there's also a way for a middleware to manually indicate "here's what I matched!" so it could be used for stats/logging, too.

**Is this something that could be improved with the new endpoint routing mechanism?** Or is there some facility I haven't found yet that already exists to solve this problem?

**Comment by JamesNK** [comment]
Not every endpoint will have a `RoutePattern` on it. For example if you're using CORS and an invalid HTTP method is received then the endpointFeature.Endpoint will be an `Endpoint` that returns a 405 response.

What you are doing, casting an Endpoint to a MatcherEndpoint (and testing that it is not null) is perfectly fine. Usually the endpoint will come from a route, but not always.

You could also place attributes on actions, which are added to an Endpoint's metadata, and use that when logging.

**Comment by tillig** [comment]
I guess I'm just hoping there's an opportunity to improve over what I see are the options today, which seem to be:

- Use `AttributeRouteInfo` where possible and, if not, make a guess assuming it's a convention-based route.
- Know about every endpoint type like `MatcherEndpoint` and try to cast. Adjust any time any change happens to routing that might add different endpoint types or extensions.
- Add a custom attribute on every controller/action that basically duplicates all the route pattern information.

I acknowledge that there are cases where there's no route. I get that. I get the CORS example, I get that middleware can grab a path and decide whether or not to handle it, etc. I'm just looking for... well, maybe a pattern or convention for where I can look to see _if_ there was a route pattern matched.

For example, could the route pattern (if matched) be added to the `Metadata` collection so I can pick it up from a well known location rather than trying to cast types and hope? If so, then I could see middleware also being able to put their own matched routes in the collection using the same convention and it'd be easier to handle. (Note the `Metadata` collection as a list rather than a dictionary or something seems like it'll still be sort of painful to use. Unclear what other than internals will be able to reasonably take advantage of that.)

Or maybe for endpoints in general the display name could be more oriented toward normalized logging and stats gathering - instead of the display name for a `MatcherEndpoint` always ending up pointing at a type like `EndpointRoutingExperiment.Controllers.ValuesController.Get (EndpointRoutingExperiment)` it could be the route template or something usable/parsable.

I'm just now digging into the new endpoint routing stuff so it's hard for me to come up with suggestions on exactly how to make it happen, I'm just really hoping there's something here that can make life easier in this area.

**Comment by JamesNK** [comment]
DisplayName is only for display. We don't want to make it parse-able.

Are you worried that there are going to be multiple endpoint types that have `RoutePattern` on them? In the next preview of ASP.NET Core 2.2 the MatcherEndpoint is being renamed to RouteEndpoint. It is the only implementation of Endpoint.

**Comment by JamesNK** [comment]
I discussed this with the team and we have no plans to change routing to use other kinds of endpoints for MVC actions. You will be safe testing the type and getting RoutePattern from RouteEndpoint (aka MatcherEndpoint)

While we could add the RoutePattern to the endpoint's metadata, it would wasteful to do it now just for a what-if scenario. And it is something we could do in the future if this ever becomes a problem.

Does this answer your question?

**Comment by tillig** [comment]
If it's reasonably safe, casting will work. I appreciate the help and follow-up on this. Thanks!
