### ISSUE TITLE
Routing does not encode / in segments

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#8]
If you have "{controller}/{action}" and new { controller = "cool/beans", action = "index" } you get "cool/beans/index".  This doesn't roundtrip via parsing, so it's almost certainly something we want to change.The System.Web implementation **does not** deal with this case. 

From @Eilon 

>I suspect that this might technically be a long-running bug in routing as well. I think technically we want to encode each URL segment and then combine those together with literal slashes. It is logically incorrect to "encode" or "decode" a URL because by definition a URL is always encoded. Only segments of a URL or query string can be encoded or decoded.

>An example of something that I think is broken is if I have a URL segment that's supposed to have a slash in it, such as blog/tags/{tagNames}, and the tagNames segment can have arbitrary text in, including slashes in the form of %2f. So the incoming URL is like /blog/tags/slice%2fdice. Assuming IIS or someone didn't already ruin the URL for us (which they might have...), we'll get tagNames="slice/dice" - that's great. But if we tried to generate the URL you'd get /blog/tags/slice/dice, which is incorrect. Hopefully this made a tiny bit of sense :smile:

**Comment by danroth27** [comment]
We would only want to fix this based on customer feedback.
