### ISSUE TITLE
Values passed to UrlBuildingContext.Buffer don't get pre-processed

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#802]
https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Internal/UriBuildingContext.cs#L97

We put a bunch of logic in `Accept` to pre-process values before they get written to the URL. Unfortunately we missed updating `Buffer` - they probably need to flow through some shared code path.

here's an example that would break.

`Foo/{bar=BAR}/{id?}`

If you had lowercase urls = true (or if you had a parameter transformer) of `bar`.

If you provide a route value for `bar` that is `BAR` and also provide a value for `id` - then it will not get processed correctly. You'd end up with `foo/BAR` instead of `foo/bar`

**Comment by JamesNK** [comment]
Does parameter transforming have this issue?

**Comment by rynowak** [comment]
Yes, and that's also fixed in my PR
