### ISSUE TITLE
Scaffold Identity

### ISSUE THREAD

**Issue by GranDanois** [aspnet/Routing#807]
Scaffold Identity does not support areas.

If you create other areas link to identity pages no longer works. 
<a asp-area="Identity" asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
gives the route /Account/Login and not /identity/Account/login

**Comment by javiercn** [comment]
@GranDanois Can you point us to the specific links that don't work?

**Comment by javiercn** [comment]
@GranDanois I tried to repro this and I wasn't able to. Could you please provide a minimalistic repro project that illustrates the problem?

**Comment by GranDanois** [comment]
No longe sure what the problem is; the notation 
<a asp-area="Identity" asp-controller="Account" asp-action="Login">
no longer works after having created other areas now I have to use 
<a asp-area="Identity" asp-page="/Account/Login">
for routing to work?
