### ISSUE TITLE
Implement a 'not allowed' constraint

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#83]
This is a companion to the 'required' constraint. This is a companion to #79 that can fixup some special cases with link generation when one route has *fewer* tokens than another.

Ex:
`{controller}/{action}`
`api/{controller}`

Imagine an MVC controller with both an `Index` and `Get (unnamed)` action. If you try to generate a link `@Url.Action("Edit", "Home")` and there is no `Edit` action, then the second route will generate the url `api/Home?action=Edit`. 

This is technically valid, but it's not what you intended when you wrote these routes. Having a constraint like `{ action = new NotAllowedRouteConstraint() }` on the second route will prevent this from happening.

**Comment by Eilon** [comment]
@rynowak a one year old bug... is this still a thing?

**Comment by rynowak** [comment]
It hasn't come up from a user. I think we're fine to close. If anyone feels like they truly need this it's a trivial sample.
