### ISSUE TITLE
Don't use marker types as metadata

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#843]
/cc @JamesNK 

So something I realised, we can't really use marker types like `ISuppressMatchingMetadata` as metadata types. We want metadata to be overridable, and you can't override the presence of something. 

I have a PR in the works to address this issue for suppress matching and suppress link generation. Are there others?

**Comment by JamesNK** [comment]
I didn't add any. Is the plan to add a boolean flag to the metadata?

**Comment by rynowak** [comment]
Yeah that's what I did in the PR. It's just future proofing really. 

We have things like this in MVC that are policies that can't be overridden (like `IAllowAnonymous`) I didn't want to bake this problem into the design of a new system.

**Comment by rynowak** [comment]
I'll resolve this once my cleanup PR is merged then. I don't think we have another others.

**Comment by rynowak** [comment]
Done.
