### ISSUE TITLE
Parameter name and parameter transformer

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#845]
re: https://twitter.com/seangwright/status/1048086101833998336

I noticed the functionality in [his convention](https://t.co/gvEITvRLCS) has different rules for controller and action.

Should parameter transformer have the name of the parameter in the signature?

```cs
    /// <summary>
    /// Defines the contract that a class must implement to transform route values while building
    /// a URI.
    /// </summary>
    public interface IOutboundParameterTransformer : IParameterPolicy
    {
        /// <summary>
        /// Transforms the specified route value to a string for inclusion in a URI.
        /// </summary>
        /// <param name="value">The parameter name.</param>
        /// <param name="value">The route value to transform.</param>
        /// <returns>The transformed value.</returns>
        string TransformOutbound(string name, object value);
    }
```

That would enable him to apply his additional rule to strip Get/Post/Delete from the action route value.

**Comment by rynowak** [comment]
My original design intent was no, because when you use it with the inline syntax you're binding it to a parameter directly in the template. Route constraints need it because they need to access the route value dictionary.

However maybe this does make sense given how we've exposed it from MVC.

**Comment by mkArtakMSFT** [comment]
@JamesNK, @rynowak is there any action we should take here?

**Comment by JamesNK** [comment]
We're not going to change this.
