### ISSUE TITLE
Split samples website into sandbox and function websites

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#857]
Split samples website into sandbox and function websites.

Discussion:
I found developing the host matcher policy without unit tests in samples a real pain. What do you think of a test project for sandbox? Alternatively dev for things like it could be something that happens in the AspLabs repo, but that would entail a new solution, web site, etc.

**Comment by rynowak** [comment]
> What do you think of a test project for sandbox? 

I think its fine as long as we're willing to throw stuff away when it's no longer relevant.
