### ISSUE TITLE
Lower kebab case routing url

### ISSUE THREAD

**Issue by Eilon** [aspnet/Routing#861]
_From @TanvirArjel on Monday, 15 October 2018 12:10:11_

In the `ConfigureServices` method of the `startup` class I am configuring as follows:

`services.AddRouting(option => option.LowercaseUrls = true);`

And it making my routing url `http://localhost:13921/Exception/ExceptionList` as follows:

`http://localhost:13921/exception/exceptionlist`

Actually it should have been:

`http://localhost:13921/exception/exception-list`

for more readability.

Thank you.

_Copied from original issue: aspnet/AspNetCore#3630_

**Comment by khellang** [comment]
This is coming as an extensibility point in 2.2, called "parameter transformers". See https://github.com/aspnet/Routing/blob/a657c3bdf2a37b07327229b89940502f058ebc95/test/Microsoft.AspNetCore.Routing.Tests/TestObjects/SlugifyParameterTransformer.cs for an example.

**Comment by JamesNK** [comment]
Yup, parameter transformers let you do this. Note that this feature is not in 2.2 preview 2. Preview 3 will have parameter transformers.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#parameter-transformer-reference

Is this what you are looking for?

**Comment by TanvirArjel** [comment]
@JamesNK  Thanks! I have few questions as follows:

1. Document says that Parameter transformers are needed to be configured using `ConstraintMap`. So in this case what will be the `ConstraintMap` value in the following code.

```
services.AddRouting(option =>
            {
                option.ConstraintMap = ?? // What will be ConstraintMap  value here?
                option.LowercaseUrls = true;
            });
```

2. Document also says:
```
routes.MapRoute(
    name: "default",
    template: "{controller=Home:slugify}/{action=Index:slugify}/{id?}");
```
With the preceding route, the action `SubscriptionManagementController.GetAll()` is matched with the URI `/subscription-management/get-all`. A parameter transformer doesn't change the route values used to generate a link. `Url.Action("GetAll", "SubscriptionManagement"`) outputs `/subscription-management/get-all`.

My proposal is it would have great if there is a option as follows instead writing `slugify` in the route template:
```
services.AddRouting(option =>
            {
                option.IsSlugify=true;
                option.LowercaseUrls = true;
            });
```

**Comment by JamesNK** [comment]
While setting an IsSlugify boolean value would be simpler in your case, it doesn't help developers support other scenarios. By supporting a developer to plug in a transformer into routing they can make routes that use camelCasing, snake_casing, slugify-casing, etc.

```cs
services.AddRouting(option =>
            {
                option.ConstraintMap["slugify"] = typeof(SlugifyParameterTransformer);
                option.LowercaseUrls = true;
            });
```

```cs
public class SlugifyParameterTransformer : IOutboundParameterTransformer
{
    public string TransformOutbound(object value)
    {
        // Slugify value
        return value == null ? null : Regex.Replace(value.ToString(), "([a-z])([A-Z])", "$1-$2").ToLower();
    }
}
```

**Comment by JamesNK** [comment]
I think all the questions have been answered. Closing.
