### ISSUE TITLE
Difference in rejected outbound route constraint behavior compared to 2.1 and endpoint routing

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Routing#862]
I have an `IRouteConstraint` like so:

```C#
public class EvenRouteConstraint : IRouteConstraint
{
    /// <inheritdoc />
    public bool Match(
        HttpContext httpContext,
        IRouter route,
        string routeKey,
        RouteValueDictionary values,
        RouteDirection routeDirection)
    {
        if (values.TryGetValue(routeKey, out var value) && value != null)
        {
            var valueString = Convert.ToString(value, CultureInfo.InvariantCulture);
            return int.TryParse(valueString, out var result) && result % 2 == 0;
        }

        return false;
    }
}
```

The action: 
```C#
[HttpGet("/[controller]/[action]/{id:even}")]
public IActionResult Index(int id) => View("/Pages/Index.cshtml");
```

and the view:

```C#
@Url.Action("Index", new { id = 2 })
@Url.Action("Index", new { id = 3 })
```

With 2.1 routing, the output is so:

> /Home/Index/2 /Home/Index/3 

With 2.2 routing, the output is so:

> /Home/Index/2 

Might be the same thing as https://github.com/aspnet/Routing/issues/728. Filing this so we're aware of the difference in behavior.

**Comment by rynowak** [comment]
Does you application also have a conventional route? I don't understand how you're setting that result in 2.1

**Comment by pranavkm** [comment]
> Does you application also have a conventional route? 

Yup, there's a conventional route with the default template. Removing it makes the two versions behave identically.

**Comment by rynowak** [comment]
hmm that's interesting, I would expect the link generator to see both templates.

**Comment by rynowak** [comment]
OK. this is definitely expected behaviour in 2.2

What's happening is that in the 2.1 case the conventional route (without constraint) can successfully generate a URL - because that's what conventional routes do. 

Conventional routes in endpoint routing don't link to actions that don't exist.
