### ISSUE TITLE
Attribute routing: GetVirtualPath() (e.g. called by Url.Action) doesn't respect constraints from IApplicationModelConvention

### ISSUE THREAD

**Issue by cypressious** [aspnet/Routing#896]
Moving from https://github.com/aspnet/AspNetCore/issues/3745

## Short version

When adding selectors with constraints using an `IApplicationModelConvention` like so

```cs
action.Selectors.Add(new SelectorModel(defaultSelector)
{
    AttributeRouteModel = localizedVersion,
    ActionConstraints =
    {
        new CultureActionConstraint { Culture = ... }
    }
});

public class CultureActionConstraint : IActionConstraint
{
    public string Culture { get; set; }

    public int Order => 0;

    public bool Accept(ActionConstraintContext context)
    {
        return CultureInfo.CurrentCulture.TwoLetterISOLanguageName == Culture;
    }
}
```

anything that calls `GetVirtualPath()` (e.g. `Url.Action()`) doesn't respect the constraints.

To reproduce, checkout and run https://github.com/cypressious/asp-net-core-localized-routes-issue, then open http://localhost:5000/about_ru?culture=ru. The generated link should be to http://localhost:5000/privacy_ru but it's actually http://localhost:5000/privacy_bg

**Comment by cypressious** [comment]
@hishamco anybody specific I should ping?

**Comment by rynowak** [comment]
Action constraints only run during action selection - they have no role during URL generation.

**Comment by rynowak** [comment]
What are you trying to accomplish?

**Comment by cypressious** [comment]
My application should run on different domains, each corresponding to a culture. Every culture has its localized routes, but I don't have the culture as part of the url. The generated links must be correct for every domain/culture, e.g. on the frontpage I have a link to the user page which is

http://your-domain.com/user for en culture
http://your-domain.de/benutzer for de culture

**Comment by BoasE** [comment]
Any news on this ? @mkArtakMSFT

**Comment by hishamco** [comment]
@BoasE Could you use my workaround that I mentioned, while the team got a time to investigate on this, because if there's a bug, will not show up until the next release, or you can using a nightly builds

Hope @mkArtakMSFT will reply to use, because he knows better than me about the team 😄

**Comment by BoasE** [comment]
The most important thing is to know wether it is a bug :)

I still see a small chance that we are just missing something on how to implement it in the supported way. 

So its mainly important to get a information wether it is a bug or if we should use the asp in an other way for this

**Comment by mkArtakMSFT** [comment]
@JamesNK, can you please look into this one as @rynowak is out.

**Comment by JamesNK** [comment]
> The most important thing is to know wether it is a bug :)

It is not a bug. Like Ryan said, action constraints only run when matching incoming requests to actions. They don't run when generating a route.

**Comment by hishamco** [comment]
@JamesNK even though if it's not a bug I'm not sure what's the secret behind `GetVirtualPath()` because it has a strange behavior. Hope you have a look to the original issue, to know what i'm talking about

**Comment by hishamco** [comment]
What made me crazy is when I did a workaround for the issue, the link with TagHelper `<a asp-action="Privacy" asp-controller="Home">Privacy</a>` point to the correct wrote, while the HtmlHelper one doesn't `@Html.ActionLink("Privacy", "Privacy", "Home")`?!!

**Comment by BoasE** [comment]
@hishamco the point i don't get is that if this is a expected behavior then this means you were not allowed to use Url.Action as soon as you have constrains because Url.Action may create Links that are not valid

@JamesNK  do you agree ?

**Comment by JamesNK** [comment]
`IActionConstraint` is not supported in URL generation. `IRouteConstraint` is supported.

Instead of a route per language against an action, have you considered having a single route with the language as a route parameter? [This post on StackOverflow](https://stackoverflow.com/a/32839796/11829) goes into setting this up in some details.

**Comment by BoasE** [comment]
@JamesNK the topic is that the page we are migrating already  has a url pattern without the culture in the parameter. changing this would break existing very well google ranked routes. So this is not an option.

The culture is only defined by the domain.

We found a solution by manually creating routes which seems to work , but it feels a little like reeinventing the wheel an d my expectation was that asp core has a easy way to manage this.
Especially my assumption was that Url.Action only generates valid urls which is not given in this scenario

**Comment by BoasE** [comment]
I think you can close it. but i want to point out that it isn't returning a **valid** url. as the url that it creates can't be called du to the constraints and therefore results in a errorcode.

But I understand its workin the way it is designed for.

**Comment by JamesNK** [comment]
You are mixing together route matching with MVC resolving the route to an action. IActionConstraint is used by MVC to resolve a matched route to an action. This step doesn't apply when generating a link so IActionConstraint is not called.

What you want to use is IRouteConstraint.

**Comment by cypressious** [comment]
@JamesNK but that's exactly the point, there's no way to add an `IRouteConstraint` using `IApplicationModelConvention`

**Comment by BoasE** [comment]
@JamesNK  do you have an example on how to add RouteConstraints instead of action constraints?

**Comment by BoasE** [comment]
Any news? @JamesNK

**Comment by JamesNK** [comment]
I linked one here - https://github.com/aspnet/Routing/issues/896#issuecomment-436156772
